### ISSUE TITLE
\CaseSwitch selects lowercase for first macro in \MakeTitlecase

### ISSUE THREAD

**Issue by moewew** [latex3/latex3#1316] opened 2023-10-31 08:51 UTC
Just so the example from https://github.com/plk/biblatex/pull/1310 does not get lost.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{etoolbox}

\begin{document}
\newrobustcmd*{\hello}{hello}
\newrobustcmd*{\helloA}{helloA}
\newrobustcmd*{\helloB}{helloB}
\newrobustcmd*{\helloC}{helloC}
\newrobustcmd*{\helloD}{helloD}
\DeclareCaseChangeEquivalent{\hello}{%
     \CaseSwitch
       {\helloA}
       {\helloB}
       {\helloC}
       {\helloD}}

\MakeLowercase{\hello}

\MakeUppercase{\hello}

\MakeTitlecase{\hello}
\end{document}
```
now produces

>helloC
>helloB
>helloC

![image of output reproduced above](https://github.com/plk/biblatex/assets/6755835/2d8bd576-a42e-4156-aa3d-3f943ba58f07)
with the updated kernel.

but used to give (for example on Overleaf with an older kernel https://www.overleaf.com/read/xbmyvpvkzchp#aaeb2c)

>helloC
>helloB
>helloD

Is that intentional?

**Comment by josephwright** [comment] 2023-10-31 08:58
I'll see if I can fix this today - we are due a release

**Comment by josephwright** [comment] 2023-11-20 10:27
The '2e part' of the issue could be fixed by changing `\text_titlecase:nn` for `\text_titlecase_first:nn` in the def. for `\MakeTitlecase`. That though doesn't sort the underlying problem - how to cover both titlecasing as 'just change the first character' and 'lowercase the remainder of the text'. I suspect we will end up needing a generic
```latex
\text_case:nnnnn { <first-char> } { <rest-of-first-word> } { <first-char-of-other-words> } { <rest-of-other-words> } 
  { <lang> } { <text> } 
```
function :(

**Comment by josephwright** [comment] 2023-11-20 11:57
One slightly out-there idea would be to have some 'lowercase except the start' function, so that `\text_weird_lowercase:n { \text_titlecase_first:n {...}  }` does the job!

**Comment by josephwright** [comment] 2023-11-20 12:38
@car222222 What @davidcarlisle  said :)

Basically, I was hoping to shift to a 'do one thing' approach and have 'titlecase' strictly separate from 'lowercase', but that's tricky when people want to combine both things, especially as we have a performance impact.

**Comment by car222222** [comment] 2023-11-20 12:53
Understood, but how do they want to "combine" such ideas/commands? 
Is it simply by applying one followed by the other?  Or in more subtle ways? 

To understand these examples, I guess I need to find out how \CaseSwitch is supposed to behave; then I can see what people do not like. In particular, what exactly is the variable that is tested by this switch? Should there even be a concept of "the current case(-changing)" to be tested?

In theory, any such "separation" would seem to be a Good Thing™. But clearly it gives "unexpected" results.

**Comment by car222222** [comment] 2023-11-20 13:05
In particular, what are both the logical/theoretical, and the actual/implemented, meaning of "being titlecase(d)", and how does one distinguish "titlecase-only-first" from "titlecase-all" in this switch?

**Comment by car222222** [comment] 2023-11-20 13:16
Thus it may be that the advertised meaning and/or the usage and implementation of such a switch needs to be (some or all of these):

refined;
properly and exhaustively defined;
extended (eg, to cover all types of title-casing);
replaced? 

Maybe such a concept of redefining a macro (on the fly), depending on some ill-defined state of some ill-defined other process is never going to work particularly well?

**Comment by josephwright** [comment] 2023-11-20 14:11
> Understood, but how do they want to "combine" such ideas/commands? Is it simply by applying one followed by the other? Or in more subtle ways?

In the original approach, `\text_titlecase:n` titlecased on the first character, then lowercasing on the remainder, whereas `\text_titlecase_first:n` just titlecased the first character. We decided that this was misleading, so have adjusted such that we have `\text_titlecase_all:n`, which titlecases the first character of each word in the input, and deprecated `\text_titlecase:n`. So the question becomes how does one achieve the 'lowercase the remainder' effect: we need it for compatibility for `\text_titlecase:n` but also more generally. I had hoped that a simple combination would work, but that misses the 'switch' business plus any characters that are affected differently by lowercase-then-titlecase than from directly titlecasing.

> To understand these examples, I guess I need to find out how \CaseSwitch is supposed to behave; then I can see what people do not like. In particular, what exactly is the variable that is tested by this switch?

The nature of the case change happening: nothing, `upper`, `lower`, `title`.

**Comment by josephwright** [comment] 2023-11-20 14:12
> In particular, what are both the logical/theoretical, and the actual/implemented, meaning of "being titlecase(d)", and how does one distinguish "titlecase-only-first" from "titlecase-all" in this switch?

You can't, because you are always doing exactly one change to a character.

**Comment by car222222** [comment] 2023-11-20 15:44
But a macro defined using the switch is not "a character", neither need it expand to a character. 

But I asked what this switch actually looks at to decide on the "current expansion": there must surely be some internal variable being checked.  
Would it help if this internal variable had a constant value throughout any type of title-casing?  As it presumably does in the other three cases (e.g., throughout \MakeUpperCase). 

What is the "nature of the case changing" and who/what decides this? And when/how is this nature set, and checked?  This all seems rather murky, and maybe confused.

**Comment by car222222** [comment] 2023-11-20 15:47
Oops, should be "the nature of the case change happening".
But that makes it more mysterious!  In what sense is it "happening" and when/how does this "happening" get set up and changed?

**Comment by car222222** [comment] 2023-11-20 15:50
Also, a macro that has a choice of what to expand to is not a character, nor does it expand to one.  So this seems to be not well-defined: does it apply only when processing a character or also when expanding random switchable macros; and how is stored or determined?

**Comment by car222222** [comment] 2023-11-20 15:52
And "title" is not a single state, but many possible ones depending on the breakdown into characters and words.  It needs a very detailed definition.

**Comment by car222222** [comment] 2023-11-20 16:02
A more precise question: suppose that the current state is "titlecase a character" but a macro is seen.  What is the defined behaviour?

**Comment by josephwright** [comment] 2023-11-20 16:28
> But I asked what this switch actually looks at to decide on the "current expansion": there must surely be some internal variable being checked. Would it help if this internal variable had a constant value throughout any type of title-casing? As it presumably does in the other three cases (e.g., throughout \MakeUpperCase).

All of `\text_...case:nn` use the same internal function, which in the current release takes _two_ arguments to indicate the approach needed. The first argument is one of  `upper`, `lower` or `title`, and is 'how to handle the first non-exempted unit' (codepoint or switching macro), the second argument is one of `upper`, `lower`, `title` or `break`, and is how to handle the second/subsequent words.

**Comment by josephwright** [comment] 2023-11-20 16:31
> Also, a macro that has a choice of what to expand to is not a character, nor does it expand to one. So this seems to be not well-defined: does it apply only when processing a character or also when expanding random switchable macros; and how is stored or determined?

`\CaseSwitch` is a mechanism we provide to deal with places that expansion-only would be an issue for non-character outcomes. If, during expansion, we encounter a macro with a definition `\ifx` equal to `\CaseSwitch`, we choose the 'output' argument based on the state `upper`/`lower`/`title`; outside of case changing the argument selected will always be the 'do nothing' one.

**Comment by car222222** [comment] 2023-11-21 12:24
Generic is usually a Good Thing™. 

This, below, looks like a very thorough approach.
Why is it problematical, deserving a frown? 

I am not sure that I can see how it helps in dealing with "switchable macros".  
When are these  expanded, and how is the switch set to the necessary value at the right time?

Would it help if both of the "rest-of-..." are fixed as "no-change"? 
Do switchable macros have this concept of "no-change"?  What exactly would remain unchanged? 

```
\text_case:nnnnn { <first-char> } 
     { <rest-of-first-word> } 
     { <first-char-of-other-words> } 
     { <rest-of-other-words> } 
  { <lang> } { <text> } 
```

**Comment by car222222** [comment] 2023-11-21 13:37
Thanks.  But that still leaves some  questions:

1.  What exactly does it mean to "apply titlecasing to a character"?
2.  Assuming that, when looking for such a character to be "title-cased", expansion is happening and so any switchable macro gets expanded to its "title" branch.  
What happens if this expansion contains no letter-like-tokens? Does the search for a character "to be titlecased" continue, or are the following characters treated as "the remainder of a word"?
What happens if this (full) expansion contains, for example, only non-letter tokens, or some letters followed by a word-break?  
Is it always simply accepted as-is, or are the resulting tokens processed any further?  
Is the first expansion (or the full expansion) simply accepted (even if it contains no letter-like tokens) and the process moves on, treating any further characters (not from the expansion) as being "in the remainder of the word", so that the first actually occurring letter-like token in the expansion will never get titlecased.  

Such cases are not covered by @davidcarlisle 's examples since they all have the "title" switch beginning with an uppercased character.

**Comment by josephwright** [comment] 2023-11-21 13:49
>     1. What exactly does it mean to "apply titlecasing to a character"?

If a Unicode titlecase mapping exists for the character, use that; if not but there is an uppercase mapping, use that; if neither of these is true, leave the character unchanged.

**Comment by davidcarlisle** [comment] 2023-11-21 13:53
@car222222  we seem to be straying way off teh bug report issue, but anyway

> Such cases are not covered by @davidcarlisle 's examples since they all have the "title" switch beginning with an uppercased character.

It is easy to adapt the example

```
\documentclass{article}

\makeatletter
\ExplSyntaxOn
\def\uc{\text_uppercase:nn{}}
\def\lc{\text_lowercase:nn{}}
\def\tc{\text_titlecase:nn{}}
\def\tf{\text_titlecase_first:nn{}}
\ExplSyntaxOff


\NewExpandableDocumentCommand\mymacro{}{my macro text}


\NewExpandableDocumentCommand\mymacrob{}{%
\CaseSwitch
{nORmal}
{uPPER}
{LOwer}
{tITLE}%
}

\begin{document}

uc \uc{\mymacrob\ xxx}

lc \lc{\mymacrob\ xxx}

tc \tc{\mymacrob\ xxx} % The issue at hand

tf \tf{\mymacrob\ xxx}

\end{document}
```

![image](https://github.com/latex3/latex3/assets/1268738/c089ca7b-45fa-4b57-b7ec-b27b37342785)


So yes, the resuts of the switch are like `\NoCaseChange` and after they are inserted processing moves on to any following tokensm, they are not further processed. The issue here is that is not happening in the third example (titlecase) as it is revealing its two-step implementation, the input is lowercased 9nd the lowercase branch of the switch is taken) then the input is reprocessed to uppercase the first resulting character.  so you get `LOwer` instead of the expected  `tITLE`

**Comment by car222222** [comment] 2023-11-21 16:10
@davidcarlisle : not entirely strayed, since it has now emerged that the switch case "title" was perhaps never a very sound idea.  

It might, even at this late stage, be best to  drop (i.e. ignore) this switch case, and to document that in a "titlecase situation" such a macro is first fully expanded via the "lowercase" switch case and then the result of that is reprocessed from the start, using only character replacement.

**Comment by davidcarlisle** [comment] 2023-11-21 16:16
@car222222  I don't think that would work and in any case for many uses the most natural form is `titlecase_first` which only touches the start of the string and doesn't lowercase the rest, and as shown here there is no issue with that form the `title` branch of the switch works as expected.

**Comment by car222222** [comment] 2023-11-21 16:25
Probably not at this stage.  What about the process of uppercasing the first character of every word? Is that OK too?

**Comment by car222222** [comment] 2023-11-21 16:33
Or can we just document that in order to get "most things lowercase" , it is safest to first explicitly lowercase the text and then explicitly apply the titlecasing (since otherwise some of these macros will not "behave as expected").

**Comment by josephwright** [comment] 2024-10-24 10:50
Looking back, I'm wondering if we can do much here for the 'historical' code - I am not sure there is more to do

**Comment by josephwright** [comment] 2024-11-05 12:37
After discussion, we are going to look again at `\MakeTitlecase` - we are likely to fix there.

**Comment by josephwright** [comment] 2024-11-05 13:12
Suggested changes to the kernel:
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{etoolbox}
\ExplSyntaxOn
\makeatletter
\cs_gset_protected:cpn { MakeLowercase \c_space_tl \c_space_tl \c_space_tl } [#1] #2
  {{
    \let \OE \oe
    \@@text@case@aux { lowercase } {#1} {#2}
  }}
\cs_gset_protected:cpn { MakeUppercase \c_space_tl \c_space_tl \c_space_tl } [#1] #2
  {{
    \let \oe \OE
    \@@text@case@aux { uppercase } {#1} {#2}
  }}
\cs_gset_protected:cpn { MakeTitlecase \c_space_tl \c_space_tl \c_space_tl } [#1] #2
  {{
    \let \oe \OE
    \@@text@case@aux { titlecase_all } {#1} {#2}
  }}
\cs_gset_protected:Npn \@@text@case@aux #1#2#3
  {
    \cs_set_nopar:Npn \reserved@a { }
    \tl_if_blank:nTF {#2}
      {
        \str_set:Nx \reserved@a
          { \BCPdata { casing } }
        \str_if_empty:NT \reserved@a
          {
            \str_set:Nx \reserved@a
              { \BCPdata { language } }
          }
      }
      { \keys_set:nn { __kernel } {#2} }
    \use:c { text_ #1 :Vn } \reserved@a {#3}
  }
\cs_generate_variant:cn { text_titlecase_all:nn } { V }
\ExplSyntaxOff

\begin{document}
\newrobustcmd*{\hello}{hello}
\newrobustcmd*{\helloA}{helloA}
\newrobustcmd*{\helloB}{helloB}
\newrobustcmd*{\helloC}{helloC}
\newrobustcmd*{\helloD}{helloD}
\DeclareCaseChangeEquivalent{\hello}{%
     \CaseSwitch
       {\helloA}
       {\helloB}
       {\helloC}
       {\helloD}}

\MakeLowercase{\hello}

\MakeUppercase{\hello}

\MakeTitlecase{\hello}
\end{document}
```
This restores the expected behaviour here, but means that `\MakeTitlecase` no longer lowercases the non-leading characters. I think that's likely the best plan - only question then is do we want `\text_titlecase_first:nn` or `\text_titlecase_all:nn` as the underlying function?

**Comment by josephwright** [comment] 2024-11-05 13:36
Thinking, I suggest we use `first` but could add a keyval to allow `all` to be selected, something like `words = first|all`

**Comment by davidcarlisle** [comment] 2024-11-09 22:23
looks good, I wonder if an optional argument fits the style here or whether to add another command `\MakeTitlecaseAll` or `\MakeAllTitlecase` or some such, but no strong opinion.

**Comment by u-fischer** [comment] 2024-11-09 22:51
@davidcarlisle  there is already an optional argument, for the locale (but it is not documented in usrguide??).

**Comment by davidcarlisle** [comment] 2024-11-09 22:59
@u-fischer  so there is, OK

**Comment by josephwright** [comment] 2024-11-10 08:47
> @davidcarlisle there is already an optional argument, for the locale (but it is not documented in usrguide??).

> The case-changing commands take an optional argument which can be used to
tailor the output. This optional argument accepts the key \texttt{locale},
also available under the alias \texttt{lang},
which can be used to give a language identifier in BCP-47
format. This is then applied to select language-specific features during
case-changing.

I think the optional arg is documented :)

**Closed** 2024-11-12 14:15 UTC
Labels: bug
