### ISSUE TITLE
\input and \file_if_exist:nTF have diffrent behaviour in lualatex when using -output-dir

### ISSUE THREAD

**Issue by Skipp1** [latex3/latex3#1070] opened 2022-03-19 22:32 UTC
Hi, all
As the title hints, \file_if_exists has a different file-finding behaviour to \input on lualatex when referencing files in -output-dir 

lualatex also shows different behaviour for \file_if_exists compared to pdflatex/xelatex/platex/uplatex 

- pdflatex  \file_if_exists -> detects file in -output-dir  
- xelatex  \file_if_exists -> detects file in -output-dir
- platex  \file_if_exists -> detects file in -output-dir
- uplatex  \file_if_exists -> detects file in -output-dir
- lualatex  \file_if_exists -> does _not_ detect file in -output-dir

However, lualatex is still able to access the files in -output-dir in via \include

**Comment by Skipp1** [comment] 2022-03-19 22:36
Minimum working example:

create the folder structure 
```
jobdir/
   | - a.tex
   | - outdir/
          | - b.tex
```
a.tex:
```
\documentclass{article}
\usepackage{expl3}
\begin{document}

\input{b.tex}

\ExplSyntaxOn
\file_if_exist:nTF { b.tex } {
	b.tex ~ exists
} {
	b.tex ~ does ~ not ~ exist
}
\ExplSyntaxOff

\end{document}
```

b.tex:
```
I am the contents of b.tex
```

Execute the command 
```
$ cd jobdir/
$ lualatex -output-dir=outdir a.tex
```

**Comment by u-fischer** [comment] 2022-03-19 23:30
The behaviour depends on the tex system. In miktex `kpse.find_file`  does find the file, but in texlive it fails. This should perhaps be reported on the texlive list.

**Comment by Skipp1** [comment] 2022-03-20 00:14
Oh yeah I should mention that I am using texlive2021 as provided by the opensuse repos

pdfTeX, Version 3.141592653-2.6-1.40.22
LuaHBTeX, Version 1.13.2
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>

**Comment by FrankMittelbach** [comment] 2022-03-20 09:46
As @u-fischer said this shows a discrepancy in the underlying engine behavior and the library for finding files  on which LaTeX relies to find files. If that is producing different results depending on platform and/or engine then obviously those also show in LaTeX, but it isn't something that can or should be masked in LaTeX but adjusted in the engines/file search library. Perhaps @kberry can tell you where this should best be reported.

**Comment by kberry** [comment] 2022-03-20 16:22
it would be very helpful for luigi to have a plain tex example using whatever primitives are underlying the l3 call. it is not easy to dig through the l3 code.

given a non-latex example, the answer to "where to report" is dev-luatex@ntg.nl (see end of luatex --help).

**Comment by kberry** [comment] 2022-03-20 16:26
maybe it is this: https://github.com/latex3/latex2e/issues/145 aka https://tug.org/pipermail/tex-k/2019-May/003014.html and the fix never got propagated to luatex.

not sure i want to hold up the release for this, but maybe.

**Comment by kberry** [comment] 2022-03-20 16:34
basic \openin example seems to work with luatex:
```
mkdir out
touch out/myoutfile.tex
luatex -output-dir=out tryout
```
where tryout.tex is:
```
\nopagenumbers
\openin1 = myoutfile.tex \ifeof1 \message{NOTFOUND}\else\message{found}\fi
\end
```
Output is "found" with both pdftex and luatex, both 2021 and 2022 binaries.

**Comment by kberry** [comment] 2022-03-20 16:52
This one-liner running with luatex prints nil:
```
\directlua{f = kpse.find_file("myoutfile.tex"); print(f);}\end
```
with same setup as above (`luatex -output-dir=out tryout`, etc.).

I mailed Luigi.

**Comment by u-fischer** [comment] 2022-03-20 16:54
@kberry The problem is the lua kpse library. E.g. this here 

~~~~
\input{child.tex}

\directlua{local file =kpse.find_file("child.tex") print("XXXX",file)}

\bye
~~~~

will give this terminal output

~~~~
C:\Users\Nililand-Surface\Documents\tests>luatex --output-dir=subfolder test-utf8
This is LuaTeX, Version 1.15.0 (TeX Live 2022)
 restricted system commands enabled.
(./test-utf8.tex (./subfolder/child.tex)XXXX    nil
~~~~

so the file is found but not by kpse. This is not new, I found a ten years old question about it.

**Comment by FrankMittelbach** [comment] 2022-03-20 16:55
all in all a different "Baustelle" :-)  closing here

**Closed by FrankMittelbach** 2022-03-20 16:55 UTC
