### ISSUE TITLE
Some "Updated:" date tags in interface3 seems outdated (e.g. tuple related additions in l3fp)

### ISSUE THREAD

**Issue by jfbu** [latex3/latex3#667] opened 2020-02-02 13:07 UTC
For example, `\fp_add:Nn` is tagged `Updated: 2012-05-08` at page 212 of interface3.pdf (dated Released 2019-11-07). But looking at commits, I found 967c578f with  date `Sun Feb 11 08:23:19 2018 -0500` which seems to be the first one introducing "tuple" data type to l3fp. I found quite a few other documentation of l3fp support macros where the documentation mentions "tuples" but the "Updated" date is not updated. (ah ah).

**Comment by josephwright** [comment] 2020-02-02 19:38
'Updated' is about API changes. I agree that for the `fp` functions, it's slightly complicated as they take a range of input which has extended over time. However, the description that they accept a floating point expression is still true.

**Comment by jfbu** [comment] 2020-02-02 20:07
ah ok, I did not know that. You mean that "updated" is only to signal possible breakage of previous usage, and thus is never updated in case of extension only?

**Comment by josephwright** [comment] 2020-02-03 22:54
@jfbu No, if there's a significant extension it normally gets marked; the issue is more that one might end up marking all `fp` functions every time a new operation is added, and that seems like overkill.

**Comment by blefloch** [comment] 2021-04-23 15:19
@josephwright  I'm not sure what I can usefully do here.  Should I close the issue since I agree with your comments above?

**Closed** 2022-03-01 22:25 UTC
Labels: expl3, documentation
