### ISSUE TITLE
Add l3doc option to not replace @@ in the PDF

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#651] opened 2019-12-19 18:12 UTC
`expl3` macro names are in general longer, and writing the code so that it doesn't produce overfull boxes when typeset gets trickier, especially because the `@@` are replaced by the package/module prefix, which makes the columns in the actual code not correspond to the columns in the typeset PDF.

For smaller modules and packages, in which the prefix is always the same, `l3doc` could have an option to disable the `@@` replacement to shorten code lines.

**Comment by josephwright** [comment] 2021-02-25 16:48
Duplicate of https://github.com/latex3/latex3/issues/416

**Closed by josephwright** 2021-02-25 16:48 UTC
Labels: enhancement, l3doc

**Comment by niruvt** [comment] 2025-03-12 09:09
Is this option released? I am on TL2025 (updated). What's the default behavior? Replacing `@@` or not replacing them?

**Comment by josephwright** [comment] 2025-03-12 10:35
We have made no changes - but please use the linked issue to discuss

**Comment by niruvt** [comment] 2025-03-12 10:48
@josephwright okay, I have commented there. Thanks.
