### ISSUE TITLE
 \__kernel_file_name_quote:e error (I think)

### ISSUE THREAD

**Issue by ondohotola** [latex3/latex3#626] opened 2019-09-09 17:15 UTC
Since yesterday I get this error

! Undefined control sequence.
<argument> \__kernel_file_name_quote:e 
                            {\tl_to_str:n {/Users/el/dns/retpdp/}NotoSans.fonts

tlmgr's log file shows

[Sun Sep  8 17:33:28 2019] update: l3backend (51962 -> 52041)
[Sun Sep  8 17:33:29 2019] update: l3kernel (51962 -> 52041)

and

for i in l3backend l3kernel
do 
	tlmgr restore --force $i 51962
done

cures it, so I assume there is an issue with the new l3kernel.

greetings, el

**Comment by josephwright** [comment] 2019-09-09 17:15
Duplicate of https://github.com/latex3/latex3/issues/624

**Closed by josephwright** 2019-09-09 17:15 UTC

**Comment by ondohotola** [comment] 2019-09-09 17:38
Thank you,

you guys are fast :-)-O

el

On 2019-09-09 19:16 , Joseph Wright wrote:
> Closed #626.
> 

-- 
Dr. Eberhard W. Lisse          / Obstetrician & Gynaecologist (Saar)
el@lisse.NA            / *     |   Telephone: +264 81 124 6733 (cell)
PO Box 8421                  /
Bachbrecht, Namibia     ;____/
