### ISSUE TITLE
[xparse] Default value reference to other arguments doesn't work for if there is an 's' argument.

### ISSUE THREAD

**Issue by Evpok** [latex3/latex3#281] opened 2015-10-20 22:29 UTC
E.g.

```
\documentclass{article}
\usepackage{xparse}
\NewDocumentCommand\spam{s m O{#2}}{
    First: #2\\
    Second: #3\\
}
\begin{document}
\spam{1}
\spam{1}[2]
\end{document}
```

doesn't work (Illegal parameter number in definition of \spam […] You meant to type ## instead of #, right?) whereas

```
\documentclass{article}
\usepackage{xparse}
\NewDocumentCommand\spam{m O{#1}}{
    First: #1\\
    Second: #2\\
}
\begin{document}
\spam{1}
\spam{1}[2]
\end{document}
```

does.

**Comment by josephwright** [comment] 2015-10-21 07:27
There's never been support for using `#1`, _etc._ in the arg. spec. The fact it works for `mo` or similar is an artefact: you'll see it fails for `om`, _etc._

**Comment by blefloch** [comment] 2015-10-21 14:35
Joseph, it could be supported without too much work, I believe.  Do you think it's worth it?  It's not the first time that I see a question about having an argument default to the value of another one.

**Comment by josephwright** [comment] 2015-10-21 14:40
@blefloch  If you think it's doable I'm sure no-one will object, but at least at present it's not part of the design of the interface

**Comment by josephwright** [comment] 2015-10-21 15:01
@blefloch  In particular, how do you plan to address the fact that we might  have  for example `#2` used before it's been parsed (with `O{#2}m`).

**Comment by FrankMittelbach** [comment] 2015-10-21 19:40
Am 21.10.15 um 17:01 schrieb Joseph Wright:
> @blefloch <https://github.com/blefloch> In particular, how do you plan
> to address the fact that we might have for example |#2| used before it's
> been parsed (with |O{#2}m|).

That's in fact the typical use case. You have an optional argument that 
has a default of a mandatory one, as in say the heading commands, and 
such optional args are usually first.

In a non-expandable way I guess I can see how to make this work, 
expandably ... hmm ... maybe @blefloch can do that as well :-)

**Comment by blefloch** [comment] 2015-10-22 12:21
Ah, I didn't think of the expandable case.  That should still be doable without much slow-down, but I don't know yet how to do some details.  The idea would be to start by collecting arguments without worrying about default values of optional arguments (probably just putting `-NoValue-` for them), then have one auxiliary (per doc command) that builds all optional arguments' default values, then some general code to replace each `-NoValue-` by these default values.

Consequences of this approach:

- It used to be possible to define `\NewDocumentCommand {\foo} {O{default}} {#1}` then do `\use:x{\foo[\char_generate:nn{45}{11}NoValue-]}` and get `-NoValue-` as an actual argument even though it matches the internal `-NoValue-` marker (with the crazy catcode of `-`).  Because of the two-pass approach to getting default values of arguments, this would now fail (give `default`).

- The spec `O{...#2...}mO{#1!}`, when given only the mandatory argument `foo` will end up with the arguments `{...foo...}{foo}{-NoValue-!}`, because the arguments are only propagated once.  Simply repeating the logic I use for propagating arguments would not work since `#3` is now not `-NoValue-` any longer.  The only way I can see would be to keep track of dependencies between arguments.  This seems out of scope of `xparse`.

- The spec `O{#3}mO{#1}` works as I would expect: a user of such a command can give two different values for optional arguments, or simply give one of the two, in which case the same value is used for both, or give neither, in which case both are `-NoValue`.

**Comment by josephwright** [comment] 2015-10-22 12:34
The NoValue marker is meant to be 'special' but not used directly: anyone doing your first line is abusing things. A failure there is entirely to be expected. The second case I think is also OK: a spec that you can use exactly `#1` but not derivatives thereof should be fine.

**Comment by FrankMittelbach** [comment] 2015-10-22 15:13
Am 22.10.15 um 14:21 schrieb Bruno Le Floch:
> Ah, I didn't think of the expandable case. That should still be doable
> without much slow-down, but I don't know yet how to do some details. The
> idea would be to start by collecting arguments without worrying about
> default values of optional arguments (probably just putting |-NoValue-|
> for them), then have one auxiliary (per doc command) that builds all
> optional arguments' default values, then some general code to replace
> each |-NoValue-| by these default values.

something along those lines - that is what I meant with two-level 
approach (if I wrote it down that is :-))

However, I think you go overboard with the "consequences"; I think the 
supported (and desired) syntax and behavior should be thought out 
beforehand further and preferably not derived by the implementation alone.

**Comment by blefloch** [comment] 2015-10-22 19:46
Joseph, my second case would also fail (with the proposed implementation) if there were no `...` nor `!` in the code: the issue is more that of having arguments `#3`'s default depend on `#1`, whose default depends on `#2`.

Frank, I agree we should define more precisely what we support.  I'm simply detailing consequences of my proposed implementation to give some idea of what is doable.  I really have no idea how much we should support, but that shouldn't stop us from supporting at least basic uses.

**Comment by josephwright** [comment] 2015-10-22 20:20
@blefloch  Ah, I see. A spec that says 'the value of a mandatory argument may be used as the default value for one or more optional arguments' would seem reasonable. That's I think by far the most likely use case and avoids loops, _etc._

**Comment by FrankMittelbach** [comment] 2015-10-23 08:17
Am 22.10.2015 um 21:46 schrieb Bruno Le Floch:
> Frank, I agree we should define more precisely what we support. I'm
> simply detailing consequences of my proposed implementation to give some
> idea of what is doable. I really have no idea how much we should
> support, but that shouldn't stop us from supporting at least basic uses.
>

understood, wasn't meant as a critique ... only that we need to be 
careful in not letting us guided by what happens in a certain 
implementation nor raising the hopes above a level that in the end we 
don't want/can sensibly support

**Comment by blefloch** [comment] 2015-10-23 14:22
I would vote for Joseph's suggestion, modified by changing "used as the default" to "used in the default".  This allows constructions such as `\NewDocumentCommand{\myacro}{mO{#2s}m}{...}` where the optional argument (meant here for the plural of a word) is a small variation of the mandatory one.

**Comment by josephwright** [comment] 2015-11-05 13:05
@blefloch  Any progress on this? Does seem like a nice feature if we can have it :-)

**Comment by blefloch** [comment] 2015-11-15 14:45
I'm very much hoping to do it today.

**Comment by blefloch** [comment] 2015-11-15 17:31
How should this reuse of arguments interact with preprocessors such as `\SplitList`?  I'm minded to make preprocessors act after the arguments are worked out, and just before running the code of the function, but I don't know how hard this will be to implement. (By the way, it doesn't look like I'll get time to resolve this issue today, sorry.)

**Comment by eg9** [comment] 2015-11-17 23:47
I had a similar dream today: an argument specifier that I'll call `q` (for “quine”) similar to `o`, but that means “use the next mandatory argument if not specified: essentially `\@dblarg`. I think a definition like

    \NewDocumentCommand{\title}{qm}
     {
      \tl_gset:Nn \g_class_metadata_shorttitle_tl { #1 }
      \tl_gset:Nn \g_class_metadata_title_tl { #2 }
     }

is much simpler than

    \NewDocumentCommand{\title}{om}
     {
      \IfNoValueTF{ #1 }
       { \tl_gset:Nn \g_class_metadata_shorttitle_tl { #2 } }
       { \tl_gset:Nn \g_class_metadata_shorttitle_tl { #1 } }
      \tl_gset:Nn \g_class_metadata_title_tl { #2 }
     }

or, more generally,

    \NewDocumentCommand{\foo}{qm}
    {
     \internal_function:nn { #1 } { #2 }
    }

instead of

    \NewDocumentCommand{\foo}{om}
     {
      \IfNoValueTF{ #1 } { \internal_function:nn { #2 } { #2 } } { \internal_function:nn { #1 } { #2 } }
     }

Of course, the proposed

    \NewCommand{O{#2}m}{...}

would do, but it's less clear, in my opinion, and prone to abuse.

**Comment by blefloch** [comment] 2015-11-22 18:04
I agree to some extent that for your use case, @eg9, your proposed `q`-type argument is clearer than `O{#2}`.  However, I think it is much too specific.  Here are a few cases where `q` would not do.

A function to define new acronyms could expect an optional argument describing how to pluralize the acronym.  By default it could be the singular plus an `s`.  I'd probably code that as something like `\DeclareDocumentCommand{\newacro}{O{plural=#2s}m}{...}`.

A document-level version of `\clist_use:Nnnn` (which gives a way to build lists like "A, B, C, D, and E", with a different separator between the last two, and for the case of only two items), with by default the same separator in all cases.  I'd code that perhaps as `\DeclareDocumentCommand{\uselist}{mO{#1}O{#2}m}{\clist_set:Nn\l_tmpa_clist{#4}\clist_use:Nnnn\l_tmpa_clist{#1}{#2}{#3}}`.

It is true that the current idea of allowing `#1` as a default may be abused, but I think the potential applications make it worth it.

**Comment by eg9** [comment] 2015-11-23 13:19
I can see the usefulness of the extended syntax, but I'm still attached to the `q` type: it would be simpler for all use cases where `\@dblarg` applies. Simpler user interface… Of course I'd like to have the extended syntax too.

**Closed** 2017-02-08 04:15 UTC
Labels: feature request, xpackages
