### ISSUE TITLE
LaTeX3 packages break in ConTeXt (LuaMetaTeX)

### ISSUE THREAD

**Issue by JairoAdelRio** [latex3/latex3#788] opened 2020-08-08 16:00 UTC
Since the last update, the following happens when expl3-generic is loaded with ConTeXt using the LuaMetaTeX engine:

```
tex error       > tex error on line 18105 in file expl3-code.tex: ! Font \c__fp_exp_intarray has only 7 fontdimen parameters

<recently read> \c__fp_exp_intarray 
                    
l.18105   }
   

<empty file>

Font parameter arrays are not automatically increased in this engine.
```

Marcel Krüger wrote about a related issue to the ConTeXt mailing list: https://www.mail-archive.com/ntg-context@ntg.nl/msg95273.html. What is curious is the fact the previous release (patching the code for catcode tables) worked fine both for LuaTeX and LuaMetaTeX. 

This remarks does not apply to ConTeXt with LuaTeX, as expl3-generic and friends work fine there.

**Comment by josephwright** [comment] 2020-08-08 16:11
Well yes @zauguin has already raised this, but as LuaMetaTeX is highly 'dynamic', it's non-trivial for us to work with. We do have a plan here, but it requires us to implement `intarray` in Lua, so it's not a quick fix.

**Comment by zauguin** [comment] 2020-08-12 12:13
As an update on this: The implementation in #790 already works in ConTeXt and therefore fixes the intarray issue, but for current luametatex versions this is not enough: `\openin/\read/\reaadline/\closein` have been replaced by Lua implementations which in multiple ways behave different then the old primitives, breaking the code for reading Unicode data files. The issues I could identify by now are:

  - ConTeXt does not use normal search paths for `\openin`, it could only find the files after I copied them into the working directory.
  - The current \endlinechar is not appended in `\read`, breaking some delimited arguments.
  - Spaces (U+20) are read with catcode other instead of space in `\readline`, again breaking delimited arguments.
  - Initial spaces are not discarded, but this didn't break anything obvious yet.

**Comment by josephwright** [comment] 2020-08-12 12:39
> As an update on this: The implementation in #790 already works in ConTeXt and therefore fixes the intarray issue,

So we should merge? Do we get a performance gain more generally?

>     * ConTeXt does not use normal search paths for `\openin`, it could only find the files after I copied them into the working directory.

Doesn't `resolvers` look up in the right places?

>     * The current \endlinechar is not appended in `\read`, breaking some delimited arguments.

Presumably we can fix that

>     * Spaces (U+20) are read with catcode other instead of space in `\readline`, again breaking delimited arguments.

Again, I assume that's an easy fix (we can search-and-replace or rescan safely)

>     * Initial spaces are not discarded, but this didn't break anything obvious yet.

Use the  `\use:n <stuff>`  approach?

**Comment by FrankMittelbach** [comment] 2020-08-12 12:47
I have the greatest respect for the work that Hans has done and is doing but I think it can't be our task to program after any  adjustment that luametatex does that breaks conventions established by TeX over 40 years. In my opinion it just means that expl3 is not going to work with that engine --- of course anybody is free to program around all that but please not inside the code that is loaded into all the other engines!

The problem seems to me next to unsolvable though. Basically for any command such as `\openin` you would need to write a replacement that mimics the TeX syntax and assign that to the corresponding expl3 function ... and as Hans has clearly stated that this engine is his playground with a lot of changes happening to suit him and his code regardless of compatibility or code by others, it will always be chasing after the modifications  made from one version to the next.

So I'm very much against seeing time spend on this (from a LaTeX Project team perspective) ---  that would be much more profitably used to  serve a huge number of users of the other main engines.

What we perhaps should do is at the end of setting up `primitives -> expl3` names we have some exit clause that loads an additional file if the engine is luametatex and that file exist. But not spend much time on filling that file with content.

**Comment by josephwright** [comment] 2020-08-12 13:13
> I have the greatest respect for the work that Hans has done and is doing but I think it can't be our task to program after any adjustment that luametatex does that breaks conventions established by TeX over 40 years. In my opinion it just means that expl3 is not going to work with that engine --- of course anybody is free to program around all that but please not inside the code that is loaded into all the other engines!

I explicitly meant as a conditional at the point of definition, as I already do for the pdfTeX-v-LuaTeX backend cases (although I may revise that plan: will raise an issue elsewhere).

> The problem seems to me next to unsolvable though. Basically for any command such as `\openin` you would need to write a replacement that mimics the TeX syntax and assign that to the corresponding expl3 function ... and as Hans has clearly stated that this engine is his playground with a lot of changes happening to suit him and his code regardless of compatibility or code by others, it will always be chasing after the modifications made from one version to the next.

I think a documented difference in file searching is OK given that this is by-design in LuaMetaTeX; the macro interface will still 'look' the same in terms of number of arguments.

> So I'm very much against seeing time spend on this (from a LaTeX Project team perspective) --- that would be much more profitably used to serve a huge number of users of the other main engines.

I see that, but I also see that @zauguin is enjoying himself! It's not a priority to support LuaMetaTeX but I'd not like to rule it out unless it becomes impossible.

> What we perhaps should do is at the end of setting up `primitives -> expl3` names we have some exit clause that loads an additional file if the engine is luametatex and that file exist. But not spend much time on filling that file with content.

I guess there's a minimal amount we need to load, for example some of the `expl3` goodies need Unicode data, so we need some form of file reading. But we could simply make various functions no-ops with LuaMetaTeX and print an error ('Talk to Hans').

**Comment by zauguin** [comment] 2020-08-12 13:41
@josephwright 
> > As an update on this: The implementation in #790 already works in ConTeXt and therefore fixes the intarray issue,
> 
> So we should merge? Do we get a performance gain more generally?

It haven't benchmarked yet, so I actually don't know how they this relate to the old implementation performance-wise.
So I will do some additional testing, then I'll mark the PR as ready.

> 
> > ```
> > * ConTeXt does not use normal search paths for `\openin`, it could only find the files after I copied them into the working directory.
> > ```
> 
> Doesn't `resolvers` look up in the right places?

I haven't really looked into it yet, I only noticed the not found messages. I could imagine that they only look for TeX files and are confused about the txt extension, but I'll have to look further. I imagine that this might get fixed upstream though.

> 
> > ```
> > * The current \endlinechar is not appended in `\read`, breaking some delimited arguments.
> > ```
> 
> Presumably we can fix that

Yes, we can just add it in the expl3 reading macros or adapt the Unicode data readers.

> 
> > ```
> > * Spaces (U+20) are read with catcode other instead of space in `\readline`, again breaking delimited arguments.
> > ```
> 
> Again, I assume that's an easy fix (we can search-and-replace or rescan safely)

Yes, it's just a matter of adding some `\detokenize` calls.

> 
> > ```
> > * Initial spaces are not discarded, but this didn't break anything obvious yet.
> > ```
> 
> Use the `\use:n <stuff>` approach?

Can you elaborate? Wouldn't `\use:n <stuff>` drop some braces at the beginning? That seems like a worse issue than the original problem. We could solve this in LuaMetaTeX with a `\use:n` variant with `#+` instead of `#1` though.

More generally though, I would tend to just accept most of these as differnt behavior of lmtx and instead adjust the UnicodeData loader. I had an older idea of experimenting with rewriting that one in Lua (there are quite some parsers for these datafiles in `lua-uni-algos` and/or luaotfload, so it should be rather streight-forward) which would solve most of the parsing issues anyway (of yourse we still have to find the files, but that probably just needs the right option...)

@FrankMittelbach 
> So I'm very much against seeing time spend on this (from a LaTeX Project team perspective) --- that would be much more profitably used to serve a huge number of users of the other main engines.

I'm trying to build a usable LaTeX format for LuaMetaTeX as a personal challenge, so there I write implementation for most of these anyway. Therefore there isn't that much additional work involved. Also some of these make sense as alternative implementations for LuaTeX too, so there is some benefit for more regular engines too.

**Comment by josephwright** [comment] 2020-08-12 13:48
> More generally though, I would tend to just accept most of these as differnt behavior of lmtx and instead adjust the UnicodeData loader. I had an older idea of experimenting with rewriting that one in Lua (there are quite some parsers for these datafiles in `lua-uni-algos` and/or luaotfload, so it should be rather streight-forward) which would solve most of the parsing issues anyway (of yourse we still have to find the files, but that probably just needs the right option...)

But then we have a different path for XeTeX, and that makes me uncomfortable: we will almost certainly get differences in what we record as 'right'. I'd much rather keep things in macros if we possibly can.

**Comment by josephwright** [comment] 2020-08-12 13:58
> I'm trying to build a usable LaTeX format for LuaMetaTeX as a personal challenge, so there I write implementation for most of these anyway. Therefore there isn't that much additional work involved. Also some of these make sense as alternative implementations for LuaTeX too, so there is some benefit for more regular engines too.

We should likely talk about the 'rules' here in terms of LuaTeX-specific approaches. For example, I see you've not used the (perhaps naive) method I would, of keeping macros and having them contain `\directlua ...`, but rather have made the functions 'primitive-like' using LuaTeX-specific definers. That's likely fine but we should agree (as they look different to `\show`, etc.)

**Comment by josephwright** [comment] 2020-08-12 14:01
I mean things like 
```lua
luacmd('intarray_count:N', function()
  tex.write(#@@_table())
end, 'global')
```
rather than
```latex
\cs_new_protected:Npx \intarray_count:N #1 
  { \exp_not:N \low_now:n { tex.write ( ... ) } }
```

**Comment by FrankMittelbach** [comment] 2020-08-12 14:01
Am 12.08.20 um 15:41 schrieb Marcel Krüger:
> @FrankMittelbach <https://github.com/FrankMittelbach>
> 
>     So I'm very much against seeing time spend on this (from a LaTeX
>     Project team perspective) --- that would be much more profitably
>     used to serve a huge number of users of the other main engines.
> 
> I'm trying to build a usable LaTeX format for LuaMetaTeX as a personal 
> challenge, so there I write implementation for most of these anyway. 
> Therefore there isn't that much additional work involved. Also some of 
> these make sense as alternative implementations for LuaTeX too, so there 
> is some benefit for more regular engines too.
> 

sure I  don't want to take away your fun :-), I  just would feel more 
comfortable with it being clearly separated out in the sources as it not 
so much something that we support as the team. Which is why I suggested 
that it moved to a single separate file in a separate repro with its own 
release cycle and only a single interface point to kernel sources to be 
loaded only when that is the  engine.

Then this repro can hold its own issue list and can have an officially 
different status in its readme etc. No problem with keeping it under 
latex3/... so that issues can be transferred if they show up in the 
wrong place. It is basically a thought of how to handle it. Perhaps we 
can have about it tomorrow.

**Comment by josephwright** [comment] 2020-08-12 14:08
> sure I don't want to take away your fun :-), I just would feel more comfortable with it being clearly separated out in the sources as it not so much something that we support as the team. Which is why I suggested that it moved to a single separate file in a separate repro with its own release cycle and only a single interface point to kernel sources to be loaded only when that is the engine. Then this repro can hold its own issue list and can have an officially different status in its readme etc. No problem with keeping it under latex3/... so that issues can be transferred if they show up in the wrong place. It is basically a thought of how to handle it. Perhaps we can have about it tomorrow.

I see the idea but the issue is that the changes affect file reading ... which makes life _hard_.

**Comment by FrankMittelbach** [comment] 2020-08-12 14:16
> I see the idea but the issue is that the changes affect file reading ... which makes life hard.

not if the changes make the primitives behave like they behave in other engines, would it? but perhaps I'm seeing this too naively.

**Comment by zauguin** [comment] 2020-08-12 14:22
> > I'm trying to build a usable LaTeX format for LuaMetaTeX as a personal challenge, so there I write implementation for most of these anyway. Therefore there isn't that much additional work involved. Also some of these make sense as alternative implementations for LuaTeX too, so there is some benefit for more regular engines too.
> 
> We should likely talk about the 'rules' here in terms of LuaTeX-specific approaches. For example, I see you've not used the (perhaps naive) method I would, of keeping macros and having them contain `\directlua ...`, but rather have made the functions 'primitive-like' using LuaTeX-specific definers. That's likely fine but we should agree (as they look different to `\show`, etc.)

Probably something to talk about tomorrow. I see the issue with show (and similar for tracing) (this is something on my wish-list for luametatex: A show_whatsit equivalent for lua functions/variables/conditionals/...), but they have the advantage of being faster, not relying on global variables (which again makes them faster) and especially in expl3, they allow the Lua code to be written without having to deal with the joys of special category codes.

**Comment by davidcarlisle** [comment] 2020-08-12 14:27
On Wed, 12 Aug 2020 at 15:16, Frank Mittelbach <notifications@github.com>
wrote:

> I see the idea but the issue is that the changes affect file reading ...
> which makes life hard.
>
> not if the changes make the primitives behave like they behave in other
> engines, would it? but perhaps I'm seeing this too naively.
>
>
>
I was just writing the same when this came in:-)

eg if \openin doesn't use kpse then the expl3 name could map to something
that does the file lookup first then opens the file found
without needing to change the unicode reader code, couldn't it?

On the more general point about luametatex support, I can see it both ways,
it's clearly rather unstable at present but I think we need to avoid the
situation we had with with luatex and xetex where we ignored them for a
decade and so when we finally pulled in support there was a lot of
contributed legacy code to support. We were lucky that conflicts between
Heiko's luatex support files and the lualatex group's luatexbase setup had
largely been resolved by that time, but that was luck rather than planning.

Of course with Marcel being on the team it's similar to fontspec and Will,
and deciding if it's core latex or a personal project is a matter of seeing
what hat you are wearing, but it's not impossible that luatex engine
support becomes "difficult" and that luametatex is the main supported
engine, so If Marcel can keep making something mostly work, I think adding
the occasional stub into the core latex code to make that easier isn't a
bad thing.

**Comment by josephwright** [comment] 2020-08-12 14:58
> Probably something to talk about tomorrow. I see the issue with show (and similar for tracing) (this is something on my wish-list for luametatex: A show_whatsit equivalent for lua functions/variables/conditionals/...), but they have the advantage of being faster, not relying on global variables (which again makes them faster) and especially in expl3, they allow the Lua code to be written without having to deal with the joys of special category codes.

On catcodes, I was thinking of the usual `\directlua{some_interface_function(...)}` only, so the issue is almost non-existent. On global variables, you mean that no documented Lua interfaces? I'm not keen on that: the reason all of the current emulation for LuaTeX is set up as it is in part is so we have documented Lua interfaces (we can't really claim they are 'purely internal', when you link from TeX to Lua). Or do I misunderstand?

(If there are speedups to have, it would be good to add them to LuaTeX, as it is slower than other engines through no fault of it's or our own.)

**Comment by josephwright** [comment] 2020-08-12 15:06
> 
> On Wed, 12 Aug 2020 at 15:16, Frank Mittelbach ***@***.***> wrote: I see the idea but the issue is that the changes affect file reading ... which makes life hard. not if the changes make the primitives behave like they behave in other engines, would it? but perhaps I'm seeing this too naively.
> I was just writing the same when this came in:-) eg if \openin doesn't use kpse then the expl3 name could map to something that does the file lookup first then opens the file found without needing to change the unicode reader code, couldn't it? On the more general point about luametatex support, I can see it both ways, it's clearly rather unstable at present but I think we need to avoid the situation we had with with luatex and xetex where we ignored them for a decade and so when we finally pulled in support there was a lot of contributed legacy code to support. We were lucky that conflicts between Heiko's luatex support files and the lualatex group's luatexbase setup had largely been resolved by that time, but that was luck rather than planning. Of course with Marcel being on the team it's similar to fontspec and Will, and deciding if it's core latex or a personal project is a matter of seeing what hat you are wearing, but it's not impossible that luatex engine support becomes "difficult" and that luametatex is the main supported engine, so If Marcel can keep making something mostly work, I think adding the occasional stub into the core latex code to make that easier isn't a bad thing.



> 
> 
> > I see the idea but the issue is that the changes affect file reading ... which makes life hard.
> 
> not if the changes make the primitives behave like they behave in other engines, would it? but perhaps I'm seeing this too naively.

To-date, we've avoided defining any 'psuedo-primitives', and the point as I understand it is that `\openin`, etc., are _gone_ not just changed. Now, we might reasonably argue that in Lua(Meta)TeX it's quite different using `luacmd()` to create a 'primitive' compared to `(\protected)\def`: the latter is a macro, the former is ... a LuaTeX-specific thing that is to all intends and purposes a primitive. But we should agree on that: one for the meeting.

**Comment by car222222** [comment] 2020-08-12 15:18
@zauguin wrote: I'm trying to build a usable LaTeX format for LuaMetaTeX as a personal challenge, so there I write implementation for most of these anyway. Therefore there isn't that much additional work involved. 

Maybe be not for you, but maybe other team members have to work hard to understand these ideas and read all this stuff!  So it does impinge in other priorities (whatever they may be).

But this issue is not the right place to discuss Team Policy wrt Context or any other of Hans' (and Marcel's?:-) toys.  

David's comment about the luatex engine getting replaced is important and relevant - and very, very worrying!

**Comment by JairoAdelRio** [comment] 2020-08-12 19:42
Well, I'm testing some packages/modules with the label `context` or a similar description for personal needs and so. IMO It's not like it's an urgent need for most ConTeXt users to have access to `expl3` goodies, but occasionally some of them do quite awesome (and useful) things, e.g. [`scontents`](https://github.com/pablgonz/scontents) avoids funny loops caused by ConTeXt buffers in special cases and `xparse` makes easier to write macros with weird arguments than the uniform, but sorta monotone landscape of `\if...argument` and `\do...empty`. If some author/maintainer says "I/We don't care about ConTeXt" (what I've had the fortune to read, although with a more polite wording), I'm fine with it. However, and as long as packages are supposed to work with ConTeXt and are "sold" with a `context` tag, I'll continue reporting issues.

**Comment by u-fischer** [comment] 2020-08-12 19:55
> However, and as long as packages are supposed to work with ConTeXt and are "sold" with a `context`

@JairoAdelRio  this sounds as if we should update some documentations. Can you tell us were you saw the context tag and got the impression that context with luametatex is supported? We should clarify that we can only support context/mkiv and only as long as it doesn't change too drastically.

**Comment by josephwright** [comment] 2020-08-12 19:57
Indeed, 'ConTeXt' is MkII with pdfTeX or MkIV with LuaTeX: I thought the entire point of LuaMetaTeX is that the format on top of it is ConTeX-like but is *not* ConTeXt.

**Comment by JairoAdelRio** [comment] 2020-08-12 20:01
> > However, and as long as packages are supposed to work with ConTeXt and are "sold" with a `context`
> 
> @JairoAdelRio this sounds as if we should update some documentations. Can you tell us were you saw the context tag and got the impression that context with luametatex is supported? We should clarify that we can only support context/mkiv and only as long as it doesn't change too drastically.

Oh, sorry. I'll explain myself better. I've read a log from a year or two ago when "ConTeXt" (I guess Mark IV) was read. LuaMetaTeX wasn't still around, so things are different now. I just report about the issue with ConTeXt *and* LuaMetaTeX so others can take note of that, whatever their reasons are.

**Comment by JairoAdelRio** [comment] 2020-08-12 20:20
@u-fischer 
I'm sure I read it elsewhere, but I found this:

https://groups.google.com/g/comp.text.tex/c/8SdO0BrhCBM/m/iBVqa3JzDAAJ 

So, unless it's a weird theoretical experiment, `expl3-generic` aims at being generic enough to be used along with ConTeXt. If LuaMetaTeX drifts apart too far from other TeX engines so `expl3-generic` doesn't work anymore, a little happy note saying "ConTeXt LMTX unsupported" would be pretty cool.

**Comment by josephwright** [comment] 2020-08-12 20:45
> 
> 
> @u-fischer
> I'm sure I read it elsewhere, but I found this:
> 
> https://groups.google.com/g/comp.text.tex/c/8SdO0BrhCBM/m/iBVqa3JzDAAJ
> 
> So, unless it's a weird theoretical experiment, `expl3-generic` aims at being generic enough to be used along with ConTeXt. If LuaMetaTeX drifts apart too far from other TeX engines so `expl3-generic` doesn't work anymore, a little happy note saying "ConTeXt LMTX unsupported" would be pretty cool.

Generic mode was sorted mainly for plain, as most 'generic' packages are mainly of interest to plain and LaTeX users. But we do our best with ConTeXt too :)

**Comment by JairoAdelRio** [comment] 2020-09-25 15:30
Hi again. New releases fail with LuaMetaTeX... again. It seems

```lua
token.command_id --somehow still in the manual
node.subtype
```

and some others are gone, so expl3-generic crashes. I remark it for the record, as LuaMetaTeX is still changing.

**Comment by josephwright** [comment] 2020-09-25 15:32
@JairoAdelRio I think @zauguin is on this, but there are complexities. Hopefully we can get it working soon-ish.

**Comment by josephwright** [comment] 2021-03-19 11:35
@zauguin  Any news here?

**Closed** 2021-11-24 09:38 UTC
