### ISSUE TITLE
Some page references not appearing properly in source3

### ISSUE THREAD

**Issue by mbertucci47** [latex3/latex3#1345] opened 2023-11-24 19:34 UTC
In source3.pdf, many commands' "End of definition for ..." ends with an undefined page reference "??". This occurs for the deprecated functions, but also some non-deprecated functions. For example, the `\sys_everyjob:` entry reads
> (End of definition for `\sys_everyjob:`, `\__sys_everyjob:n`, and `\g__sys_everyjob_tl`. This function is documented on page ??.)

These commands also aren't hyperlinked to their place in the documentation, so I'm assuming they simply aren't in the main documentation but a reference is being called anyways. Another example is `\use:x` which is not in the main documentation (assumedly since it's been soft-deprecated for `\use:e`).
> (End of definition for `\use:x`. This function is documented on page ??.)

Similarly with primitives like `\tex_filesize:D`.

**Comment by josephwright** [comment] 2023-11-25 10:16
Looks like that should be `\__sys_everyjob:w` - I guess I'll need to fix

**Comment by mbertucci47** [comment] 2023-11-25 16:58
I just want to clarify that it's not a one-off issue. The undefined references are there for `\msg_error:nnee`, `\pdf_version_compare:Nn`, `\l_text_accents_tl`, `get_luadata`, just to name a few.

**Comment by muzimuzhi** [comment] 2023-11-26 00:57
"This function is documented on page xxx." is typeset by `l3doc` if
- none of `macro` environment options `internal` or `int` are specified and
- the name of function doesn't contain `__`.
https://github.com/latex3/latex3/blob/ad0e6b16d9ddbc9d35573a96c2b1637495ace08f/l3kernel/l3doc.dtx#L3399-L3418
https://github.com/latex3/latex3/blob/ad0e6b16d9ddbc9d35573a96c2b1637495ace08f/l3kernel/l3doc.dtx#L2346-L2368

The undefined page references "??" in `source3.pdf` may have to be addressed in a number of ways:
- Add `macro` env option `internal`/`int`
- Add documentation
- Rename functions to be internal
- Relax conditions for determination of internal functions in `l3doc`

**Comment by mbertucci47** [comment] 2023-11-26 02:22
To that list I'll add one more. For variants documented together like in l3basics.dtx
```
% \begin{macro}
%   {\msg_error:nnee, \msg_error:nne, \msg_error:nn}
```
I think this needs an appropriate `[documented-as=\msg_error:nn]` option, since (I'm guessing) only the base macro `\msg_error:nn` is recognized as documented.

**Comment by josephwright** [comment] 2023-11-26 11:43
> I just want to clarify that it's not a one-off issue. The undefined references are there for `\msg_error:nnee`, `\pdf_version_compare:Nn`, `\l_text_accents_tl`, `get_luadata`, just to name a few.

Sure: but these will all be things we've overlooked rather than being an issue with the detection code

**Comment by josephwright** [comment] 2023-11-26 11:57
Also 4b0b1082a9fc6a3acb3d8c28b05f9e7118829d3f

**Comment by josephwright** [comment] 2023-11-26 11:58
@mbertucci47  Key point is if you log them as issues, we can fix

**Comment by josephwright** [comment] 2023-11-26 12:03
> `l_text_accents_tl`,

Deprecated .... and here really needs to be defined where they are as they still have to be _used_ inside the non-deprecated functions (@muzimuzhi).

**Comment by josephwright** [comment] 2023-11-26 12:03
> Similarly with primitives like `\tex_filesize:D`.

`:D` so expected: documented by the engines

**Comment by mbertucci47** [comment] 2023-11-26 17:16
> @mbertucci47 Key point is if you log them as issues, we can fix

@josephwright Just so I make sure I understand, do you mean a separate issue for each instance or class of instances, or just list them all here? Obviously I don't want to flood the issue tracker with a dozen or more tiny issues.

Here is the list of commands with undefined references that I will separate into multiple issues if need be.

#### primitives
- `\tex_strcmp:D`
- `\tex_Ucharcat:D`
- `\tex_filesize:D`
- `\tex_mdfivesum:D`
- `\tex_filemoddate:D`
- `\tex_filedump:D`

#### deprecated commands
- `\use:x`
- `\iow_shipout_x:Nn`
- `.str_set_x:N` and `.str_gset_x:N`
- `.tl_set_x:N` and `.tl_gset_x:N`
- `\l_text_accents_tl` and `\l_text_letterlike_tl`
- `\pdf_object_new:nn` and `\pdf_object_write:nn`
- `\cs_argument_spec:N`
- `\bool_case_true:nTF`
- `\str_lower_case:n`, `\str_upper_case:n`, and `\str_fold_case:n`
- `\str_declare_eight_bit_encoding:nnn`
- `\seq_indexed_map_inline:Nn` and `\seq_indexed_map_function:NN`
- `\seq_mapthread_function:NNN`
- `\seq_set_map_x:NNn` and `\seq_gset_map_x:NNn`
- `\sys_load_deprecation:`
- `\text_titlecase:n` and `\text_titlecase:nn`
- `\tl_lower_case:n` and others
- `\tl_case:NnTF`
- `\tl_build_clear:N` and `\tl_build_gclear:N`
- `\char_to_utfviii_bytes:n`
- `\char_to_nfd:N` and `\char_to_nfd:n`
- `\char_lower_case:N` and others
- `\peek_catcode_ignore_spaces:NTF` and others

#### commands in a list
- `\msg_error:nnee`, `\msg_error:nne`, and `\msg_error:nn`
- `\cs_generate_from_arg_count:NNno` and `\cs_replacement_spec:c`
- `\sys_everyjob:`, `\__sys_everyjob:n`, and `\g__sys_everyjob_tl`

#### lua functions
- `md5.HEX`
- `register_luadata`

#### flags
- `str_byte` and `str_error`
- `str_overflow` and `str_end`

#### other
- `\regex_case_replace_all:nNTF`
- `\__kernel_codepoint_case:nn` and others

**Comment by josephwright** [comment] 2023-11-26 20:44
> @josephwright Just so I make sure I understand, do you mean a separate issue for each instance or class of instances, or just list them all here? Obviously I don't want to flood the issue tracker with a dozen or more tiny issues.

@mbertucci47 Here is fine if you have a 'set'.

> #### primitives

Not expected to be linked: we have no docs for primitives.

> #### deprecated commands

Again, expected

> #### commands in a list
>
>     * `\msg_error:nnee`, `\msg_error:nne`, and `\msg_error:nn`
 >
>     * `\cs_generate_from_arg_count:NNno` and `\cs_replacement_spec:c`

Fixed I hope by adding `documented-as`.

>     * `\sys_everyjob:`, `\__sys_everyjob:n`, and `\g__sys_everyjob_tl`

I'll likely move this to `__kernel` as a holding position: it's not quite as easy to fix as some of the others.

> #### lua functions
> 
>     * `md5.HEX`
> 
>     * `register_luadata`

Fixed by marking as `int`.

> #### flags
> 
>     * `str_byte` and `str_error`
> 
>     * `str_overflow` and `str_end`

Moved to internal (flags used to be internal-only, hence the oversight).

> #### other
> 
>     * `\regex_case_replace_all:nNTF`

Name corrected

>     * `\__kernel_codepoint_case:nn` and others

These are documented in `l3kernel-extras`, which is then typeset only in the source part ...

**Comment by mbertucci47** [comment] 2023-11-26 20:59
> Not expected to be linked: we have no docs for primitives.

Wouldn't it be better then if there were some option for `\begin{macro}` that prevented the "This function is documented on..." from being generated? I guess primitives are not "internal" but for this purpose it should be the same as the `int` option. Similarly for deprecated commands the sentence should be suppressed.

**Comment by mbertucci47** [comment] 2023-11-26 21:03
For "`\__kernel_codepoint_case:nn` and others", I think the issue is that something is not being converted because in the list of commands in the margin there's a not-greyed-out `\@_case:nn` which should be `\__codepoint_case:nn`. Perhaps missing `@`?

**Comment by josephwright** [comment] 2023-11-27 07:53
> > Not expected to be linked: we have no docs for primitives.
> 
> Wouldn't it be better then if there were some option for `\begin{macro}` that prevented the "This function is documented on..." from being generated? I guess primitives are not "internal" but for this purpose it should be the same as the `int` option. Similarly for deprecated commands the sentence should be suppressed.

This one is I guess the trickiest, as we don't even mark up most of the primitives: the few you've spotted are there as they are Lua emulations. I'll see what others feel about the best approach here.

**Comment by davidcarlisle** [comment] 2023-11-27 16:24
> I'll see what others feel about the best approach here.

I don't mind too much how it appears, but I'd agree with @mbertucci47 that on principle generating broken links is bad form.

for the primitives can't we detect the `\tex_whatever:D` form and skip the link, or replace with a suitable boilerplate?

**Comment by FrankMittelbach** [comment] 2023-11-27 17:27
flagged in the source I mean.

**Comment by josephwright** [comment] 2023-11-27 19:15
> > performace probably isn't too much of an issue as it only affects a few people, us mostly:-), but rather than looking for `\tex_...D` it's probably enough to simply check the pageref data and if that's empty skip the whole line. That would be pretty fast
> 
> but in general you wouldn't want this I think. The fact that something is public means it should have some documentation (at least that was @wspr's idea I think) and so this is a reminder that something is missing.

The only cases that it applies to are `\tex_..:D` where we are emulating in Lua - I'm not sure those need to be showing up ...

**Comment by josephwright** [comment] 2023-11-28 08:45
> but instead of generally scanning for some pattern we could have and option called "nodoc" or something that indicates it is not documented elsewhere and drops the line, couldn't we?

Don't you think that's asking for people skipping stuff a bit too generally? The current rules are reasonably clear and we have `int` already for stuff that is internal-but-not-picked up (Lua functions, classical 2e constructs, etc.).

**Comment by muzimuzhi** [comment] 2023-11-28 18:28
I'm against introduction of `\_codedoc_if_macro_primitive:n` (https://github.com/latex3/latex3/commit/3d0ed204ef69e1517d210ecf5b071a10b1639c34) because it adds a check to _every_ command but only serves fewer than a dozen of them.
https://github.com/latex3/latex3/blob/863443a75fad05a39fbab933323af3cc1bd76ee4/l3kernel/l3doc.dtx#L3354-L3365

**Comment by josephwright** [comment] 2023-11-28 20:10
> I'm against introduction of `\_codedoc_if_macro_primitive:n` 

Assuming you agree we should fix broken links, we need something here. Solutions I can see

- Don't mark up these sections at all - feels poor
- Mark them as `int` - again, feels misleading
- Introduce some new switch - feels odd as they can be auto-detected

**Comment by FrankMittelbach** [comment] 2023-11-28 20:29
agree with the first too, but I have no problems with the last (which is why I suggested nodoc). After all, even a primitive is something that for one reason or the other may get documentation, so autodetection gets you only that far and explicitly marking the few cases where we don't want a documentation other than the code sems ok to ke (and I'm not that worried that it gets misused ... people who don't want to document somehting don't anyway and they probably do not bother with int or nodoc

**Comment by davidcarlisle** [comment] 2023-11-28 20:39
@josephwright  one other possibility

* add somewhere an appendix of tex primitives faked in Lua and document these things to give a target to link to

**Comment by josephwright** [comment] 2023-11-28 20:47
> @josephwright one other possibility
> 
>     * add somewhere an appendix of tex primitives faked in Lua and document these things to give a target to link to

Fair point, but that's in some ways more work than @FrankMittelbach's plan.

**Comment by josephwright** [comment] 2023-11-29 22:24
Do people like the latest approach?

**Comment by muzimuzhi** [comment] 2023-11-29 23:37
Yes I prefer this way.
https://github.com/latex3/latex3/blob/f0f19892d4540765cf9ad39a5cdd2770332616c2/l3kernel/l3names.dtx#L1464

TODO: Update `l3doc` documentation when the code level change is done.

**Comment by josephwright** [comment] 2023-11-30 08:03
> > Do people like the latest approach?
> 
> @josephwright happy enough :-) but I'm not too keen on the option name `undocumented`, it sounds ot me as if the documentation is missing and will come eventually, not that we think the only documentation necessary is the code documentation. What about something like `nouserdoc` (doesn't read so well perhaps -- maybe there are better suggestions) but I don't exist.

That was mainly what I was asking :) Perhaps `skip-documentation`/`skip-doc`, `suppress-doc-check`, `skip-doc-check`, ...

**Comment by FrankMittelbach** [comment] 2023-11-30 08:21
my point was that we decided it needs no doc in the user doc section so why not say that? `no-user-doc` if you prefer a more readable string. supressing the check is a side-effect not the "cause" in my opinion.

**Comment by josephwright** [comment] 2023-11-30 08:24
> my point was that we decided it needs no doc in the user doc section so why not say that? `no-user-doc` if you prefer a more readable string. supressing the check is a side-effect not the "cause" in my opinion.

You said we might need other name suggestions :) We could focus on the fact there is no link back to the user part: `no-doc-link` or `skip-doc-ref`, but I'm not unhappy with `no-user-doc` - just seeing if anything else reads better.

**Comment by mbertucci47** [comment] 2023-12-12 15:14
With the recent update there is a new issue with the page references. Many commands have a space in their name and the references are undefined. For example,
> End of definition for `\token _to_meaning:N`. This function is documented on page ??.

Note the space after `\token`. Similarly for `\msg _error:nnnn`, `\iow _log:n`, and so on. Not sure if this should be a new issue.

**Comment by josephwright** [comment] 2023-12-12 15:25
OK, it looks like this is happening where we are documenting a variant which is defined independent of the base function, e.g. 
```
% \begin{macro}[documented-as = \cs_generate_from_arg_count:NNnn]
%    {\cs_generate_from_arg_count:NNno}
% \begin{macro}[documented-as = \cs_replacement_spec:N]{\cs_replacement_spec:c}
%   A couple of variants that are from early functions.
%    \begin{macrocode}
\cs_generate_variant:Nn \cs_generate_from_arg_count:NNnn { NNno }
\cs_generate_variant:Nn \cs_replacement_spec:N { c }
%    \end{macrocode}
% \end{macro}
% \end{macro}
```
So the issue is the `documented-as` setup or perhaps the arg. grabbing.

**Comment by mbertucci47** [comment] 2024-01-06 18:04
I think `\tl_build_get:NN` is missing a `deprecated` option in l3deprecation.dtx. Otherwise source3 looks good and perhaps this can be closed?

**Closed** 2024-01-07 19:09 UTC
