### ISSUE TITLE
\vbox_set_top_to_ht?

### ISSUE THREAD

**Issue by lvjr** [latex3/latex3#922] opened 2021-05-16 01:29 UTC
There are `\vbox_set_top` and `\vbox_set_to_ht` in `l3box`, but not `\vbox_set_top_to_ht`.

**Comment by blefloch** [comment] 2021-05-16 07:08
This is a duplicate of #552, so I'll close here, but I'm implementing it now.

**Closed by blefloch** 2021-05-16 07:08 UTC
Labels: duplicate
