### ISSUE TITLE
Problem with last update and hobby tikzlibrary

### ISSUE THREAD

**Issue by nignasi** [latex3/latex3#282] opened 2015-10-22 15:42 UTC
After last update in my MikTeX system, following code fails:

``` tex
\documentclass[a4paper, 12pt]{report}
\usepackage{tikz}
\usetikzlibrary{hobby}

\listfiles
\begin{document}
\end{document}
```

%---------------------------------------------------------------------

Log file: 

```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9 64-bit) (preloaded format=pdflatex 2015.9.14)  22 OCT 2015 17:32
entering extended mode
**sensetitol-10.tex
(sensetitol-10.tex
LaTeX2e <2015/01/01> patch level 2
Babel <3.9m> and hyphenation patterns for 69 languages loaded.
(C:\miktex\tex\latex\base\report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(C:\miktex\tex\latex\base\size12.clo
File: size12.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@chapter=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(C:\miktex\tex\latex\pgf\frontendlayer\tikz.sty
(C:\miktex\tex\latex\pgf\basiclayer\pgf.sty
(C:\miktex\tex\latex\pgf\utilities\pgfrcs.sty
(C:\miktex\tex\generic\pgf\utilities\pgfutil-common.tex
\pgfutil@everybye=\toks14
\pgfutil@tempdima=\dimen103
\pgfutil@tempdimb=\dimen104

(C:\miktex\tex\generic\pgf\utilities\pgfutil-common-lists.tex))
(C:\miktex\tex\generic\pgf\utilities\pgfutil-latex.def
\pgfutil@abb=\box26

(C:\miktex\tex\latex\ms\everyshi.sty
Package: everyshi 2001/05/15 v3.00 EveryShipout Package (MS)
))
(C:\miktex\tex\generic\pgf\utilities\pgfrcs.code.tex
Package: pgfrcs 2015/08/07 v3.0.1a (rcs-revision 1.31)
))
Package: pgf 2015/08/07 v3.0.1a (rcs-revision 1.15)

(C:\miktex\tex\latex\pgf\basiclayer\pgfcore.sty
(C:\miktex\tex\latex\graphics\graphicx.sty
Package: graphicx 2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)

(C:\miktex\tex\latex\graphics\keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks15
)
(C:\miktex\tex\latex\graphics\graphics.sty
Package: graphics 2014/10/28 v1.0p Standard LaTeX Graphics (DPC,SPQR)

(C:\miktex\tex\latex\graphics\trig.sty
Package: trig 1999/03/16 v1.09 sin cos tan (DPC)
)
(C:\miktex\tex\latex\00miktex\graphics.cfg
File: graphics.cfg 2007/01/18 v1.5 graphics configuration of teTeX/TeXLive
)
Package graphics Info: Driver file: pdftex.def on input line 94.

(C:\miktex\tex\latex\pdftex-def\pdftex.def
File: pdftex.def 2011/05/27 v0.06d Graphics/color for pdfTeX

(C:\miktex\tex\generic\oberdiek\infwarerr.sty
Package: infwarerr 2010/04/08 v1.3 Providing info/warning/error messages (HO)
)
(C:\miktex\tex\generic\oberdiek\ltxcmds.sty
Package: ltxcmds 2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
)
\Gread@gobject=\count88
))
\Gin@req@height=\dimen105
\Gin@req@width=\dimen106
)
(C:\miktex\tex\latex\pgf\systemlayer\pgfsys.sty
(C:\miktex\tex\generic\pgf\systemlayer\pgfsys.code.tex
Package: pgfsys 2014/07/09 v3.0.1a (rcs-revision 1.48)

(C:\miktex\tex\generic\pgf\utilities\pgfkeys.code.tex
\pgfkeys@pathtoks=\toks16
\pgfkeys@temptoks=\toks17

(C:\miktex\tex\generic\pgf\utilities\pgfkeysfiltered.code.tex
\pgfkeys@tmptoks=\toks18
))
\pgf@x=\dimen107
\pgf@y=\dimen108
\pgf@xa=\dimen109
\pgf@ya=\dimen110
\pgf@xb=\dimen111
\pgf@yb=\dimen112
\pgf@xc=\dimen113
\pgf@yc=\dimen114
\w@pgf@writea=\write3
\r@pgf@reada=\read1
\c@pgf@counta=\count89
\c@pgf@countb=\count90
\c@pgf@countc=\count91
\c@pgf@countd=\count92
\t@pgf@toka=\toks19
\t@pgf@tokb=\toks20
\t@pgf@tokc=\toks21

(C:\miktex\tex\generic\pgf\systemlayer\pgf.cfg
File: pgf.cfg 2008/05/14  (rcs-revision 1.7)
)
Driver file for pgf: pgfsys-pdftex.def

(C:\miktex\tex\generic\pgf\systemlayer\pgfsys-pdftex.def
File: pgfsys-pdftex.def 2014/10/11  (rcs-revision 1.35)

(C:\miktex\tex\generic\pgf\systemlayer\pgfsys-common-pdf.def
File: pgfsys-common-pdf.def 2013/10/10  (rcs-revision 1.13)
)))
(C:\miktex\tex\generic\pgf\systemlayer\pgfsyssoftpath.code.tex
File: pgfsyssoftpath.code.tex 2013/09/09  (rcs-revision 1.9)
\pgfsyssoftpath@smallbuffer@items=\count93
\pgfsyssoftpath@bigbuffer@items=\count94
)
(C:\miktex\tex\generic\pgf\systemlayer\pgfsysprotocol.code.tex
File: pgfsysprotocol.code.tex 2006/10/16  (rcs-revision 1.4)
))
(C:\miktex\tex\latex\xcolor\xcolor.sty
Package: xcolor 2007/01/21 v2.11 LaTeX color extensions (UK)
 (C:\miktex\tex\latex\00miktex\color.cfg
File: color.cfg 2007/01/18 v1.5 color configuration of teTeX/TeXLive
)
Package xcolor Info: Driver file: pdftex.def on input line 225.
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1337.
Package xcolor Info: Model `hsb' substituted by `rgb' on input line 1341.
Package xcolor Info: Model `RGB' extended on input line 1353.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1355.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1356.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1357.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1358.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1359.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1360.
) (C:\miktex\tex\generic\pgf\basiclayer\pgfcore.code.tex
Package: pgfcore 2010/04/11 v3.0.1a (rcs-revision 1.7)

(C:\miktex\tex\generic\pgf\math\pgfmath.code.tex
(C:\miktex\tex\generic\pgf\math\pgfmathcalc.code.tex
(C:\miktex\tex\generic\pgf\math\pgfmathutil.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathparser.code.tex
\pgfmath@dimen=\dimen115
\pgfmath@count=\count95
\pgfmath@box=\box27
\pgfmath@toks=\toks22
\pgfmath@stack@operand=\toks23
\pgfmath@stack@operation=\toks24
)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.code.tex
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.basic.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.trigonometric.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.random.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.comparison.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.base.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.round.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.misc.code.tex)
(C:\miktex\tex\generic\pgf\math\pgfmathfunctions.integerarithmetics.code.tex)))
(C:\miktex\tex\generic\pgf\math\pgfmathfloat.code.tex
\c@pgfmathroundto@lastzeros=\count96
))
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorepoints.code.tex
File: pgfcorepoints.code.tex 2013/10/07  (rcs-revision 1.27)
\pgf@picminx=\dimen116
\pgf@picmaxx=\dimen117
\pgf@picminy=\dimen118
\pgf@picmaxy=\dimen119
\pgf@pathminx=\dimen120
\pgf@pathmaxx=\dimen121
\pgf@pathminy=\dimen122
\pgf@pathmaxy=\dimen123
\pgf@xx=\dimen124
\pgf@xy=\dimen125
\pgf@yx=\dimen126
\pgf@yy=\dimen127
\pgf@zx=\dimen128
\pgf@zy=\dimen129
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorepathconstruct.code.tex
File: pgfcorepathconstruct.code.tex 2013/10/07  (rcs-revision 1.29)
\pgf@path@lastx=\dimen130
\pgf@path@lasty=\dimen131
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorepathusage.code.tex
File: pgfcorepathusage.code.tex 2014/11/02  (rcs-revision 1.24)
\pgf@shorten@end@additional=\dimen132
\pgf@shorten@start@additional=\dimen133
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorescopes.code.tex
File: pgfcorescopes.code.tex 2015/05/08  (rcs-revision 1.46)
\pgfpic=\box28
\pgf@hbox=\box29
\pgf@layerbox@main=\box30
\pgf@picture@serial@count=\count97
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcoregraphicstate.code.tex
File: pgfcoregraphicstate.code.tex 2014/11/02  (rcs-revision 1.12)
\pgflinewidth=\dimen134
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcoretransformations.code.tex
File: pgfcoretransformations.code.tex 2015/08/07  (rcs-revision 1.20)
\pgf@pt@x=\dimen135
\pgf@pt@y=\dimen136
\pgf@pt@temp=\dimen137
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorequick.code.tex
File: pgfcorequick.code.tex 2008/10/09  (rcs-revision 1.3)
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcoreobjects.code.tex
File: pgfcoreobjects.code.tex 2006/10/11  (rcs-revision 1.2)
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorepathprocessing.code.tex
File: pgfcorepathprocessing.code.tex 2013/09/09  (rcs-revision 1.9)
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorearrows.code.tex
File: pgfcorearrows.code.tex 2015/05/14  (rcs-revision 1.43)
\pgfarrowsep=\dimen138
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcoreshade.code.tex
File: pgfcoreshade.code.tex 2013/07/15  (rcs-revision 1.15)
\pgf@max=\dimen139
\pgf@sys@shading@range@num=\count98
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcoreimage.code.tex
File: pgfcoreimage.code.tex 2013/07/15  (rcs-revision 1.18)

(C:\miktex\tex\generic\pgf\basiclayer\pgfcoreexternal.code.tex
File: pgfcoreexternal.code.tex 2014/07/09  (rcs-revision 1.21)
\pgfexternal@startupbox=\box31
))
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorelayers.code.tex
File: pgfcorelayers.code.tex 2013/07/18  (rcs-revision 1.7)
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcoretransparency.code.tex
File: pgfcoretransparency.code.tex 2013/09/30  (rcs-revision 1.5)
)
(C:\miktex\tex\generic\pgf\basiclayer\pgfcorepatterns.code.tex
File: pgfcorepatterns.code.tex 2013/11/07  (rcs-revision 1.5)
)))
(C:\miktex\tex\generic\pgf\modules\pgfmoduleshapes.code.tex
File: pgfmoduleshapes.code.tex 2014/03/21  (rcs-revision 1.35)
\pgfnodeparttextbox=\box32
)
(C:\miktex\tex\generic\pgf\modules\pgfmoduleplot.code.tex
File: pgfmoduleplot.code.tex 2015/08/03  (rcs-revision 1.13)
)
(C:\miktex\tex\latex\pgf\compatibility\pgfcomp-version-0-65.sty
Package: pgfcomp-version-0-65 2007/07/03 v3.0.1a (rcs-revision 1.7)
\pgf@nodesepstart=\dimen140
\pgf@nodesepend=\dimen141
)
(C:\miktex\tex\latex\pgf\compatibility\pgfcomp-version-1-18.sty
Package: pgfcomp-version-1-18 2007/07/23 v3.0.1a (rcs-revision 1.1)
))
(C:\miktex\tex\latex\pgf\utilities\pgffor.sty
(C:\miktex\tex\latex\pgf\utilities\pgfkeys.sty
(C:\miktex\tex\generic\pgf\utilities\pgfkeys.code.tex))
(C:\miktex\tex\latex\pgf\math\pgfmath.sty
(C:\miktex\tex\generic\pgf\math\pgfmath.code.tex))
(C:\miktex\tex\generic\pgf\utilities\pgffor.code.tex
Package: pgffor 2013/12/13 v3.0.1a (rcs-revision 1.25)

(C:\miktex\tex\generic\pgf\math\pgfmath.code.tex)
\pgffor@iter=\dimen142
\pgffor@skip=\dimen143
\pgffor@stack=\toks25
\pgffor@toks=\toks26
))
(C:\miktex\tex\generic\pgf\frontendlayer\tikz\tikz.code.tex
Package: tikz 2015/08/07 v3.0.1a (rcs-revision 1.151)

(C:\miktex\tex\generic\pgf\libraries\pgflibraryplothandlers.code.tex
File: pgflibraryplothandlers.code.tex 2013/08/31 v3.0.1a (rcs-revision 1.20)
\pgf@plot@mark@count=\count99
\pgfplotmarksize=\dimen144
)
\tikz@lastx=\dimen145
\tikz@lasty=\dimen146
\tikz@lastxsaved=\dimen147
\tikz@lastysaved=\dimen148
\tikzleveldistance=\dimen149
\tikzsiblingdistance=\dimen150
\tikz@figbox=\box33
\tikz@figbox@bg=\box34
\tikz@tempbox=\box35
\tikz@tempbox@bg=\box36
\tikztreelevel=\count100
\tikznumberofchildren=\count101
\tikznumberofcurrentchild=\count102
\tikz@fig@count=\count103

(C:\miktex\tex\generic\pgf\modules\pgfmodulematrix.code.tex
File: pgfmodulematrix.code.tex 2013/09/17  (rcs-revision 1.8)
\pgfmatrixcurrentrow=\count104
\pgfmatrixcurrentcolumn=\count105
\pgf@matrix@numberofcolumns=\count106
)
\tikz@expandcount=\count107

(C:\miktex\tex\generic\pgf\frontendlayer\tikz\libraries\tikzlibrarytopaths.code
.tex
File: tikzlibrarytopaths.code.tex 2008/06/17 v3.0.1a (rcs-revision 1.2)
))) (C:\miktex\tex\latex\hobby\tikzlibraryhobby.code.tex
(C:\miktex\tex\latex\hobby\pgflibraryhobby.code.tex
(C:\miktex\tex\latex\hobby\hobby.code.tex
(C:\miktex\tex\latex\l3kernel\expl3.sty
Package: expl3 2015/10/14 v6210 L3 programming layer (loader) 

(C:\miktex\tex\latex\l3kernel\expl3-code.tex
Package: expl3 2015/10/14 v6210 L3 programming layer (code) 
L3 Module: l3bootstrap 2015/09/30 v6139 L3 Bootstrap code
L3 Module: l3names 2015/10/10 v6209 L3 Namespace for primitives
L3 Module: l3basics 2015/09/22 v6033 L3 Basic definitions
L3 Module: l3expan 2015/09/10 v5983 L3 Argument expansion
L3 Module: l3tl 2015/09/29 v6121 L3 Token lists
L3 Module: l3str 2015/09/20 v6021 L3 Strings
L3 Module: l3seq 2015/08/05 v5777 L3 Sequences and stacks
L3 Module: l3int 2015/09/25 v6089 L3 Integers
\c_max_int=\count108
\l_tmpa_int=\count109
\l_tmpb_int=\count110
\g_tmpa_int=\count111
\g_tmpb_int=\count112
L3 Module: l3quark 2015/08/17 v5855 L3 Quarks
L3 Module: l3prg 2015/10/09 v6208 L3 Control structures
\g__prg_map_int=\count113
L3 Module: l3clist 2015/09/02 v5901 L3 Comma separated lists
L3 Module: l3token 2015/09/28 v6114 L3 Experimental token manipulation
L3 Module: l3prop 2015/08/05 v5777 L3 Property lists
L3 Module: l3msg 2015/09/28 v6113 L3 Messages
L3 Module: l3file 2015/09/23 v6037 L3 File and I/O operations
\l_iow_line_count_int=\count114
\l__iow_target_count_int=\count115
\l__iow_current_line_int=\count116
\l__iow_current_word_int=\count117
\l__iow_current_indentation_int=\count118
L3 Module: l3skip 2015/09/25 v6089 L3 Dimensions and skips
\c_zero_dim=\dimen151
\c_max_dim=\dimen152
\l_tmpa_dim=\dimen153
\l_tmpb_dim=\dimen154
\g_tmpa_dim=\dimen155
\g_tmpb_dim=\dimen156
\c_zero_skip=\skip43
\c_max_skip=\skip44
\l_tmpa_skip=\skip45
\l_tmpb_skip=\skip46
\g_tmpa_skip=\skip47
\g_tmpb_skip=\skip48
\c_zero_muskip=\muskip10
\c_max_muskip=\muskip11
\l_tmpa_muskip=\muskip12
\l_tmpb_muskip=\muskip13
\g_tmpa_muskip=\muskip14
\g_tmpb_muskip=\muskip15
L3 Module: l3keys 2015/09/23 v6037 L3 Key-value interfaces
\g__keyval_level_int=\count119
\l_keys_choice_int=\count120
L3 Module: l3fp 2015/08/25 v5890 L3 Floating points
\c__fp_leading_shift_int=\count121
\c__fp_middle_shift_int=\count122
\c__fp_trailing_shift_int=\count123
\c__fp_big_leading_shift_int=\count124
\c__fp_big_middle_shift_int=\count125
\c__fp_big_trailing_shift_int=\count126
\c__fp_Bigg_leading_shift_int=\count127
\c__fp_Bigg_middle_shift_int=\count128
\c__fp_Bigg_trailing_shift_int=\count129
L3 Module: l3box 2015/08/09 v5822 L3 Experimental boxes
\c_empty_box=\box37
\l_tmpa_box=\box38
\l_tmpb_box=\box39
\g_tmpa_box=\box40
\g_tmpb_box=\box41
L3 Module: l3coffins 2015/08/06 v5789 L3 Coffin code layer
\l__coffin_internal_box=\box42
\l__coffin_internal_dim=\dimen157
\l__coffin_offset_x_dim=\dimen158
\l__coffin_offset_y_dim=\dimen159
\l__coffin_x_dim=\dimen160
\l__coffin_y_dim=\dimen161
\l__coffin_x_prime_dim=\dimen162
\l__coffin_y_prime_dim=\dimen163
\c_empty_coffin=\box43
\l__coffin_aligned_coffin=\box44
\l__coffin_aligned_internal_coffin=\box45
\l_tmpa_coffin=\box46
\l_tmpb_coffin=\box47
\l__coffin_display_coffin=\box48
\l__coffin_display_coord_coffin=\box49
\l__coffin_display_pole_coffin=\box50
\l__coffin_display_offset_dim=\dimen164
\l__coffin_display_x_dim=\dimen165
\l__coffin_display_y_dim=\dimen166
L3 Module: l3color 2014/08/23 v5354 L3 Experimental color support
L3 Module: l3candidates 2015/10/09 v6208 L3 Experimental additions to l3kernel
\l__box_top_dim=\dimen167
\l__box_bottom_dim=\dimen168
\l__box_left_dim=\dimen169
\l__box_right_dim=\dimen170
\l__box_top_new_dim=\dimen171
\l__box_bottom_new_dim=\dimen172
\l__box_left_new_dim=\dimen173
\l__box_right_new_dim=\dimen174
\l__box_internal_box=\box51
\l__coffin_bounding_shift_dim=\dimen175
\l__coffin_left_corner_dim=\dimen176
\l__coffin_right_corner_dim=\dimen177
\l__coffin_bottom_corner_dim=\dimen178
\l__coffin_top_corner_dim=\dimen179
\l__coffin_scaled_total_height_dim=\dimen180
\l__coffin_scaled_width_dim=\dimen181
L3 Module: l3sys 2015/09/25 v6087 L3 Experimental system/runtime functions
L3 Module: l3luatex 2015/09/10 v5983 L3 Experimental LuaTeX-specific functions
)
(C:\miktex\tex\latex\l3kernel\l3unicode-data.def
File: l3unicode-data.def 2015/07/20 v5676 L3 Unicode data
)
(C:\miktex\tex\latex\l3kernel\l3pdfmode.def
File: l3pdfmode.def 2015/09/10 v5983 L3 Experimental driver: PDF mode
\l__driver_color_stack_int=\count130
))
(C:\miktex\tex\latex\l3packages\xparse\xparse.sty
Package: xparse 2015/10/14 v6210 L3 Experimental document command parser
\l__xparse_current_arg_int=\count131
\l__xparse_m_args_int=\count132
\l__xparse_mandatory_args_int=\count133
\l__xparse_processor_int=\count134
\l__xparse_v_nesting_int=\count135
)
(C:\miktex\tex\latex\hobby\pml3array.sty
\l_array_base_int=\count136
\l_array_top_int=\count137
\l_array_tmp_int=\count138
\g_array_base_int=\count139


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/command-not-defined"
! 
! Control sequence \__msg_show_variable:Nnn undefined.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

l.185 ...riant:Nn \__msg_show_variable:Nnn { Nno }

? s
OK, entering \scrollmode...
)
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyVersion with sig. '' on line 41.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyDate with sig. '' on line 45.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \HobbyDisableAux with sig. '' on line 59.
.................................................
\l_hobby_npoints_int=\count140
\l_hobby_draw_int=\count141
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyinit with sig. 'mmm' on line 669.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyaddpoint with sig. 'm' on line 699.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbysetparams with sig. 'm' on line 705.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbygenpath with sig. '' on line 721.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbygenifnecpath with sig. 'm' on line 732.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbygenuseifnecpath with sig. 'm' on line 744.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyusepath with sig. 'm' on line 748.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbysavepath with sig. 'm' on line 751.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyrestorepath with sig. 'm' on line 756.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyshowpath with sig. 'm' on line 761.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbygenusepath with sig. '' on line 767.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining command \hobbyclearpath with sig. '' on line 770.
.................................................
)))
No file sensetitol-10.aux.
LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
ABD: EveryShipout initializing macros (C:\miktex\tex\context\base\supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
\scratchcounter=\count142
\scratchdimen=\dimen182
\scratchbox=\box52
\nofMPsegments=\count143
\nofMParguments=\count144
\everyMPshowfont=\toks27
\MPscratchCnt=\count145
\MPscratchDim=\dimen183
\MPnumerator=\count146
\makeMPintoPDFobject=\count147
\everyMPtoPDFconversion=\toks28
) (sensetitol-10.aux)

 *File List*
  report.cls    2014/09/29 v1.4h Standard LaTeX document class
  size12.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
    tikz.sty    2015/08/07 v3.0.1a (rcs-revision 1.151)
     pgf.sty    2015/08/07 v3.0.1a (rcs-revision 1.15)
  pgfrcs.sty    2015/08/07 v3.0.1a (rcs-revision 1.31)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
  pgfrcs.code.tex
 pgfcore.sty    2010/04/11 v3.0.1a (rcs-revision 1.7)
graphicx.sty    2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
graphics.sty    2014/10/28 v1.0p Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    1999/03/16 v1.09 sin cos tan (DPC)
graphics.cfg    2007/01/18 v1.5 graphics configuration of teTeX/TeXLive
  pdftex.def    2011/05/27 v0.06d Graphics/color for pdfTeX
infwarerr.sty    2010/04/08 v1.3 Providing info/warning/error messages (HO)
 ltxcmds.sty    2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
  pgfsys.sty    2014/07/09 v3.0.1a (rcs-revision 1.48)
  pgfsys.code.tex
pgfsyssoftpath.code.tex    2013/09/09  (rcs-revision 1.9)
pgfsysprotocol.code.tex    2006/10/16  (rcs-revision 1.4)
  xcolor.sty    2007/01/21 v2.11 LaTeX color extensions (UK)
   color.cfg    2007/01/18 v1.5 color configuration of teTeX/TeXLive
 pgfcore.code.tex
pgfcomp-version-0-65.sty    2007/07/03 v3.0.1a (rcs-revision 1.7)
pgfcomp-version-1-18.sty    2007/07/23 v3.0.1a (rcs-revision 1.1)
  pgffor.sty    2013/12/13 v3.0.1a (rcs-revision 1.25)
 pgfkeys.sty    
 pgfkeys.code.tex
 pgfmath.sty    
 pgfmath.code.tex
  pgffor.code.tex
    tikz.code.tex
   hobby.code.tex
   expl3.sty    2015/10/14 v6210 L3 programming layer (loader) 
expl3-code.tex    2015/10/14 v6210 L3 programming layer 
l3unicode-data.def    2015/07/20 v5676 L3 Unicode data
l3pdfmode.def    2015/09/10 v5983 L3 Experimental driver: PDF mode
  xparse.sty    2015/10/14 v6210 L3 Experimental document command parser
pml3array.sty    
supp-pdf.mkii
 ***********

 ) 
Here is how much of TeX's memory you used:
 18505 strings out of 493673
 375319 string characters out of 3151282
 367985 words of memory out of 3000000
 21670 multiletter control sequences out of 15000+200000
 3938 words of font info for 15 fonts, out of 3000000 for 9000
 1025 hyphenation exceptions out of 8191
 55i,1n,99p,10420b,293s stack positions out of 5000i,500n,10000p,200000b,50000s

No pages of output.
PDF statistics:
 3 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 500000)
 13 words of extra memory for PDF output out of 10000 (max. 10000000)
```

**Comment by josephwright** [comment] 2015-10-22 15:44
This is a 'known issue' and I will try to sort it soon. Essentially, the problem is that a sub-package here is using an internal function (` \__msg_show_variable:Nnn`) as it provides a kernel-like data type, but as the function is internal we've dropped it with no notice. The best solution needs a little thought.

**Comment by blefloch** [comment] 2015-10-22 19:51
The `hobby` package seems to be using other internals of `expl3`.  Does anyone know if it has a bug tracker to list changes that must be made?

**Comment by josephwright** [comment] 2015-10-22 20:15
@blefloch  I know the author. The problem really stems from the fact he wanted/needed another 'low level' data type so modelled the functions on existing ones. That's then been a problem as we've changed things. It's not clear to me how best to handle that type of situation: there are performance reasons for writing new data types, after all.

**Comment by wspr** [comment] 2017-11-15 12:27
I just tried this out on an up-to-date system with no error, so closing this here. Let us know if the issue recurs.

**Closed by wspr** 2017-11-15 12:27 UTC
Labels: not-us
