### ISSUE TITLE
Default value of unknown key

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#67] opened 2012-02-10 05:31 UTC
I would expect

```
\keys_define:nn { my-keys }
  {
    unknown .default:n = x ,
    unknown .code:n = \tl_show:n {#1}
  }
\keys_set:nn { my-keys } { some-key }
```

to show the default value `x`. Instead, the given default value is ignored, and I see an empty token list.

**Comment by josephwright** [comment] 2015-07-22 16:14
Fixed by recent changes.

**Comment by mlhetland** [comment] 2019-04-16 09:18
I can't quite seem to find the current status on this. Above, @josephwright says that `\setup[ligatures={}]` and `\setup[ligatures]` is the same, but that doesn't seem to be the case, anymore? Or? At least, providing an `{}` argument seems to suppress the `.default:n`? If so, the question remains: How does one canonically emulate this behavior with an `unknown` key? (And, for that matter—though not relevant to me at the moment—how does one unset a key, now?)

**Comment by mlhetland** [comment] 2019-04-16 09:31
Hm. Now I see that the default is indeed supplied to `unknown`! I guess my test was flawed. (I would still be interested in how to determine whether the default was in fact used, without using a marker default value, for example, but I guess that's not that relevant here.)

**Comment by josephwright** [comment] 2019-05-05 06:54
@mlhetland When I said that `\setup[ligatures={}]` and `\setup[ligatures]` are the same, I meant in the absence of a default value. The thing is that `.unknown` keys just don't have a default at all: I'm really not sure it makes sense. (The normal reason for allowing unknown keys is precisely to use the information as-given.(

Perhaps you might point to a use case in a new issue?

**Comment by mlhetland** [comment] 2019-05-05 07:30
Not sure if it's worth an issue … In my case, I'm adding Beamer overlay specifications to keys, so in this case, you'd have, say, `\setup{key<1-3>}` or `\setup{key<1-3>=val}`. In my `unknown` handler, I extract the relevant information, and call, resp., `\only<1-3>{\setup{key}}` or `\only<1-3>{\setup{key=val}}`.

In this case, I cannot trust that `\setup{key}` and `\setup{key={}}` are the same. What I'm doing at the moment is just using the current `.unknown` semantics, so `\setup{key<1-3>={}}` results in `\only<1-3>{\setup{key}}`, i.e., there's no way of actually supplying an empty value (rather than the absene of one). If, instead, I could specify that the default was some marker value other than `{}`, then I wouldn't have that restriction.

For that matter, I have needed to know whether a value was supplied or not in other cases, a well (there, too, using a sentinel default value); it might be useful to have a separate mechanism for that, perhaps.

If you think this merits an issue, I could open one – if not, I'll just keep using what I've got. It's not that often I need to supply an explicit empty value, anyway :-)

**Comment by Skillmon** [comment] 2023-12-27 19:31
It would be trivial to make this feature unneeded and still cover 100% of the functionality: Make `\l__keys_no_value_bool` public. It is set anyway early on, no need to alter the handling of any other key, and you got a simple way to check whether there was a value. Otherwise: Add the `.default:n` handler for `unknown`.

Use case: *Any* key forwarding whatsoever. And yes, key forwarding is a common use case. So please, reopen this.

**Comment by josephwright** [comment] 2023-12-28 11:00
Whilst I feel that `l3keys` current model (keys are properties so always have a value, and thus `key` and `key =` are equivalent), I am happy to see what the wider team feel.

**Comment by davidcarlisle** [comment] 2023-12-28 11:21
I think the most natural behaviour is for a "default" value to be applied when no value is supplied and not otherwise so `\setup[ligatures={}]`   would have value empty  `\setup[ligatures]` would have a specified default

**Comment by josephwright** [comment] 2023-12-28 11:23
> I think the most natural behaviour is for a "default" value to be applied when no value is supplied and not otherwise so `\setup[ligatures={}]` would have value empty `\setup[ligatures]` would have a specified default

That should be what already happens

**Comment by davidcarlisle** [comment] 2023-12-28 11:27
> That should be what already happens

That's what I thought (Can't check here:-) but isn't what you seemed to imply by 

"When I said that \setup[ligatures={}] and \setup[ligatures] are the same,"  but I just noticed you later qualified by " I meant in the absence of a default value."  so all good I think.

**Comment by Skillmon** [comment] 2023-12-28 11:41
The issue is not for already defined keys! I don't argue about their behaviour (in which case you can anyways use `.default:V = \c_novalue_tl` and use `\tl_if_novalue:nTF` to check if you so wish).

The issue is about handling *undefined* keys *correctly* in case we want to forward them (something that comes up as a use case every now and then, and just doesn't work with the current model in case you want to trigger the correct default value of another set, current use case -- admittedly one a bit strange -- is for instance https://tex.stackexchange.com/questions/705795/). There are two possible solutions to this, either allow a `.default:n` for the `unknown`-handler, or make `\l__keys_no_value_bool` public. Both solutions would work, but the latter comes at zero cost and zero code complexity (though the former would be more in line with the rest of `l3keys`' key=value model).

**Comment by muzimuzhi** [comment] 2023-12-28 14:27
I find allowing `.default:n` for `unknown` key tricky.

Before, in `<code>` in `unknown .code:n = <code>`, both `#1` and `\l_keys_key_tl` represent or hold the value passed to an unknown key. If no value is passed, both of them are empty.

Then if `unknown .default:n = <default unknown value>` is set and respected, at least one of `#1` and `\l_keys_key_tl` should hold `<default unknown value>`. If only one changes, then these two differ; if both change, then there's no way to know if the value is passed to the unknown key or comes from `<default unknown value>`.

Make `\l__keys_no_value_bool` public through for instance `\keys_if_no_value:TF` seems easier to understand and use. There are already variables like `\l_keys_value_tl` and `\l_keys_key_str` that are only available in a key code, thus adding a function with similar restriction is not weird. (Maybe allowing the `unknown` handler in form of a normal key rather than a key property is not the best choice.)

**Comment by Skillmon** [comment] 2023-12-28 15:26
@muzimuzhi I think you're mixing up `\l_keys_value_tl` and `\l_keys_key_tl`... And that both hold the same value even if it is caused by `.default:n` is semantically correct and should then be the case (and you could always use `.default:V = \c_novalue_tl`, which can't be directly entered by a user, and is also used by `ltcmd`, so that seems fine to me).

Regarding the variable: Why add another function which is just less versatile? `\bool_if:NTF \l_keys_no_value_bool` is not complicated. But `\bool_lazy_and:nnTF` and friends aren't well-documented for a conditional if it's not a predicate, so you end up adding 4 functions (`p`, `TF`, `T`, and `F`) for functionality that already comes free of cost. And the boolean variable would arguably be more in line with the other variables such as `\l_keys_key_str`, after all they also have no accessor function.

**Comment by mlhetland** [comment] 2023-12-28 17:27
Regarding my comments above, I don’t really need a default value; my main issue is determining whether I’m encountering `some-unknown-key` or `some-unknown-key={}` (so the `\l_keys_no_value_bool`-based solution would probably be fine).

**Comment by mlhetland** [comment] 2023-12-28 17:35
Or, to strip it down in my case (and to get a bit off topic, I guess), I’d really just like to be able to add Beamer overlays to my keys.

**Comment by muzimuzhi** [comment] 2023-12-29 02:22
> @muzimuzhi I think you're mixing up `\l_keys_value_tl` and `\l_keys_key_tl`...

@Skillmon Yes I mistyped `\l_keys_value_tl` as `\l_keys_key_tl` in https://github.com/latex3/latex3/issues/67#issuecomment-1871225144.

**Comment by Skillmon** [comment] 2023-12-29 10:51
@mlhetland both are usable for your requirements, as `.default:V = \c_novalue_tl` and then a `\tl_if_novalue:nTF` is as good as `\bool_if:NTF \l_keys_no_value_bool` (there is a slight performance difference, but afterall if you're using `beamer` and its overlays that performance difference shouldn't matter much).

**Comment by mlhetland** [comment] 2023-12-29 14:45
Absolutely.

**Comment by Skillmon** [comment] 2024-01-02 14:43
Code that would allow the `.default:n` property to be set for an unknown key:

```latex
\ExplSyntaxOn
\cs_set_protected:Npn \__keys_execute_unknown:
  {
    \bool_if:NTF \l__keys_only_known_bool
      { \__keys_store_unused: }
      {
        \cs_if_exist:cTF
          { \c__keys_code_root_str \l__keys_module_str / unknown }
          {
            %% START of added code
            \bool_if:NT \l__keys_no_value_bool
              {
                \cs_if_exist:cT
                  { \c__keys_default_root_str \l__keys_module_str / unknown }
                  {
                    \tl_set_eq:Nc
                      \l_keys_value_tl
                      { \c__keys_default_root_str \l__keys_module_str / unknown }
                  }
              }
            %% END of added code
            \__keys_execute:no { \l__keys_module_str / unknown } \l_keys_value_tl
          }
          {
            \msg_error:nnee { keys } { unknown }
              \l_keys_path_str \l__keys_module_str
          }
      }
  }

\keys_define:nn { myset }
  {
    unknown .code:n =
      \tl_if_novalue:nTF {#1}
        { \keys_set:no { myotherset } \l_keys_key_str }
        { \keys_set:no { myotherset } { \l_keys_key_str = {#1} } }
    ,unknown .default:V = \c_novalue_tl
  }
\keys_define:nn { myotherset }
  {
    foo .code:n = \typeout{Foo~ got~ #1}
    ,foo .default:n = baz
  }
\keys_set:nn { myset }
  {
    foo,
    foo = bar
  }
\stop
```

With this setup the `unknown`'s `.default:n` should take precedent over the inherited default value (as would be the case with directly set default values of defined keys).

I still think the preferable route is to make `\l__keys_no_value_bool` documented and user-level, but now you really got the choice. I can open a PR with the version you prefer if you want me to.

**Comment by josephwright** [comment] 2024-01-02 15:13
> I still think the preferable route is to make `\l__keys_no_value_bool` documented and user-level, but now you really got the choice. I can open a PR with the version you prefer if you want me to.

I know :)

My concern with this remains that it changes the model, basically. At the moment, for `l3keys` keys are properties which therefore always have a value, even if it's empty. Thus `key` with no value at all is equal to `key = `. If you make `\l__keys_no_value_bool` public, even with 'only use for forwarding' warnings, you will find people using the two with different meaning. Personally I'm not a fan, but what I think is essential is that this is a decision that isn't made by accident: I'd like to see what the consensus of the team as a whole is. I've missed this week's team meeting: I'll add to the next agenda unless @davidcarlisle, @FrankMittelbach, etc.  chime in.

**Comment by Skillmon** [comment] 2024-01-02 15:56
Well, the only reason why I prefer the boolean variable is because it's simple. If it weren't already there I'd go for the `.default:n` route.  And now that's here as well. So I agree, the team should decide.

**Comment by josephwright** [comment] 2024-01-02 17:18
@Skillmon  I think a default should work _even if_ we make the other change - so could you put in a PR for that aspect?

**Closed** 2024-01-03 13:52 UTC
Labels: enhancement, l3keys
