### ISSUE TITLE
Documentation: Text shoots off page

### ISSUE THREAD

**Issue by moewew** [latex3/latex3#696] opened 2020-04-08 07:15 UTC
The contents of p. 257 (2020-04-06, Part XXXIII: `l3text`, sec 1.2 *Case changing*) of `interface3.pdf` overprint into the footer area and even shoot off the page.

![p257overshot](https://user-images.githubusercontent.com/6755835/78754975-ac2eb500-7978-11ea-8462-a7d312e74c1c.png)

I was quite interested to read the lost content, so I thought I might as well report this here, in case something can be done about it.

The previous page 256 is completely empty, which also seems a bit odd.

**Comment by u-fischer** [comment] 2020-04-08 07:23
Clear case of a too large box (the used environment `function` boxes its content).

**Comment by Skillmon** [comment] 2020-04-08 08:42
Maybe adding an `unboxed` option to the `function` environment is a good idea (I have no idea whether this is already possible).

**Comment by PhelypeOleinik** [comment] 2020-04-08 12:34
Thanks for the report. As Ulrike says, the environment typesets everything into a box, which most of the time is a good thing, to avoid splitting a small description into even smaller bits.

I'll fix this as soon as I can.

I'll close this issue as duplicate of #666.

**Closed** 2020-04-08 12:34 UTC
Labels: bug, duplicate, l3doc

**Comment by moewew** [comment] 2020-04-08 14:55
Urgh, sorry for the duplicate. I should have searched for the page number ...

**Comment by PhelypeOleinik** [comment] 2020-04-08 15:01
@moewew Don't worry. It's understandable one wouldn't want to get near issue #666 ;-)
