### ISSUE TITLE
File ended while scanning use of \__iow_wrap_end_chunk:w

### ISSUE THREAD

**Issue by jszhao** [latex3/latex3#492] opened 2018-10-20 09:33 UTC
After update to the latest l3kernel, I have encountered the error message:
```
File ended while scanning use of \__iow_wrap_end_chunk:w
```
Here are the two minimal examples
```
\documentclass{standalone}
\usepackage{xeCJK}
\setCJKfamilyfont{wb}{FZWeiBei-S03}
\begin{document}
English
\end{document}
```
The error message is:
```
Runaway argument?
76543210\q_stop newline - 'small caps'  (m/sc) with NFSS spec.: ^^I^^O\ETC.
! File ended while scanning use of \__iow_wrap_end_chunk:w.
<inserted text>
```

The another example:
```
\documentclass{standalone}
\usepackage{xeCJK}
\setCJKmonofont[ItalicFont=KaiTi]{FangSong}
\begin{document}
English
\end{document}
```
```
Runaway argument?
76543210\q_stop newline  ^^I^^O^^W^^_^^W^^R^^A^^Pnewline  This font f\ETC.
! File ended while scanning use of \__iow_wrap_end_chunk:w.
<inserted text>
```

Although they may be related with xeCJK package, I reported here since they occurred after updating l3kernel. And I searching google, the only page that contains  `\__iow_wrap_end_chunk:w` points me to this project.

**Comment by davidcarlisle** [comment] 2018-10-20 09:36
I think this is a https://github.com/latex3/latex3/issues/491 which is fixed in the sources, sorry for the inconvenience.

**Comment by josephwright** [comment] 2018-10-20 12:30
Duplicate of #491.

**Closed by josephwright** 2018-10-20 12:30 UTC
Labels: bug, duplicate, expl3
