### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by Stone-Zeng** [latex3/latex3#460] opened 2018-05-05 09:46 UTC
Please consider to add a changelog, just like LaTeX2e, where there is a Change History at the end of `source2e.pdf`.

Currently, change information are only given at the functions descriptions. Sometimes it's important to get access to *all* the changed things.

Or, a `CHANGELOG` file in GitHub repository may be enough.

**Comment by josephwright** [comment] 2018-05-05 09:47
Erm, that's what the Git log is for ...

**Comment by wspr** [comment] 2018-05-11 12:10
I like the idea but I'm not sure we currently have enough info in our sources to auto-generate...

**Comment by josephwright** [comment] 2018-05-11 13:35
@wspr  Depends what exactly is wanted: we can just take the Git log and add that periodically, but if you want more like the 2e changes they have to be done by hand (Git checkins can be various 'non-important' items).

**Comment by FrankMittelbach** [comment] 2018-05-11 14:06
@josephwright a git log is easy to obtain but on the whole fairly useless because it contains too much irrelevant data. For a detailed check that is fone but get an overview a biased, possibly incompete changelog done by hand as we do in 2e provides imho a much better value (for most use cases).

In my understanding the request is for a moderated change log (which is extra manual work). That it probably rewarding and in the long run a good source of information but something one has to get used to providing as an extra step.

**Comment by josephwright** [comment] 2018-05-11 14:08
@FrankMittelbach  Sure, it's just a question of what we want to do. For example, I use the Git log to create summaries for releases, but I'm wary that they will soon end up as a _lot_ of lines (plus I tend to do them as an overview for the entire repo).

**Comment by FrankMittelbach** [comment] 2018-05-11 14:35
true -- I was not claiming we are in disagreement about the different options and their use.

**Comment by josephwright** [comment] 2018-05-11 14:39
Obvious questions

- Where do we want this (in a PDF, just as a `.txt`, in the distribution or just on GitHub)
- (Linked to above) Do we want one log, one per bundle, one per package, ...
- Is it done on an 'ongoing' basis or during release
- What exactly 'counts' (new functions, API changes, internal changes) and how much detail (dates?)
- Do we keep stuff 'for ever' or do we make it rolling

**Comment by blefloch** [comment] 2018-05-11 18:35
Wait, what is the application?

We may want to retrofit l3syntax-changes for that?

**Comment by FrankMittelbach** [comment] 2018-05-12 00:36
@blefloch are you referring to my answer to @josephwright which for some reason doesn't show here? if so I was just talking about the simple emacs function `add-change-log-entry`

here are my comments once more:

my gut-based answers (in case we want to do it at all)

>   * Where do we want this (in a PDF, just as a |.txt|, in the
>     distribution or just on GitHub)

in the distribution as .txt

>   * (Linked to above) Do we want one log, one per bundle, one per
>     package, ...

per bundle

>   * Is it done on an 'ongoing' basis or during release

ongoing base if one does make changes it is best to judge then

>   * What exactly 'counts' (new functions, API changes, internal changes)
>     and how much detail (dates?)

the 2e approach is to do anything "interesting" which normally means internal changes only if the expectation is that this can hit somebody
and yes, dates are useful

>   * Do we keep stuff 'for ever' or do we make it rolling

'for ever' as that is one of the long term gains: a somewhat consolidated / moderated log.


all the above really comes from using the corresponding emacs function which makes maintaining a log like in the 2e cases simple.

but I'm not sure we are up to that, it is really up to those doing most of the mods these days so all that is more a question for you and Bruno to decide, all I was saying is that I see its use in the 2e case and people check things this way as it is much easier to rescan such a moderated log for a change that could be the cause of an issue than to go through a huge git log (at least  initially)

**Comment by blefloch** [comment] 2018-05-12 05:18
I was asking what is the goal of keeping track of a changelog.

It looks like a huge amount of work that I very much suspect will be
patchy at best (my fault, certainly).  The only way to avoid that is if
there is an automatic check.  For instance l3doc could check that all
functions that are marked as updated or added in the last year appear in
some entry of the changelog file.  We tend to be reasonably good at
keeping the "updated" date correct, because of locality: the data to
change is in a place that we're changing anyways, hence looking at.

Something like a text file with

* 2020-01-01: optimize simple conditionals
  (affects \prg_new_conditional:Npnn, \prg_set_conditional:Npnn,
\prg_new_conditional:Nnn, \prg_set_conditional:Nnn)
* 2019-01-01: change boolean expressions to be greedy
  (affects \bool_if:nTF, \bool_set:Nn)

> but I'm not sure we are up to that, it is really up to those doing most
> of the mods these days so all that is more a question for you and Bruno
> to decide, all I was saying is that I see its use in the 2e case and
> people check things this way as it is much easier to rescan such a
> moderated log for a change that could be the cause of an issue than to
> go through a huge git log (at least initially)

I'm not super keen on maintaining that, so I'm certain we need some
automated checking for it to have any chance of remaining up to date.

**Comment by Stone-Zeng** [comment] 2018-05-12 05:27
IMO only important changes (e.g. new features, deprecated functions, critical behavior changes, etc) should be put into the changelog. Tracking other things in git log is enough.

**Comment by blefloch** [comment] 2018-05-12 05:34
> IMO only important changes (e.g. new features, deprecated functions,
> critical behavior changes, etc) should be put into the changelog.
> Tracking other things in git log is enough.

Then run 'texdoc l3syntax-changes' (or look at
l3kernel/l3syntax-changes.tex in our repository).  I recently updated it.

**Comment by josephwright** [comment] 2018-05-12 15:00
I can log all of that when I write release notes: might be easier than everyone having to edit every time they commit (and would have the release dates rather than the commit dates).

**Comment by Evpok** [comment] 2018-05-16 11:49
At this point it feels relevant to mention https://keepachangelog.com

**Comment by josephwright** [comment] 2018-05-16 11:55
@Evpok The thing is though you end up duplicating the same information as in the revision control, plus of course for us we already have 'added' and 'updated' dates for functions, so one can tell from the interface documents what the minimal version one needs is to get a particular behaviour. That all said, it's not a big issue to provide one: what I'm still not clear on is the exact form. For example, we could use the LaTeX2e approach and add `\changes` to the sources, such that they get added to the PDFs. Or I can put the release notes into a change log. Or we can write a change log for any significant additions as they happen. At present it seems we are going for the second option ...

**Comment by josephwright** [comment] 2018-05-16 12:03
I'll make a start on this for releases since the start of the year: older releases can be done if required (a question of reading the CTAN RSS)

**Comment by Evpok** [comment] 2018-05-16 12:16
@josephwright I meant it more as a “hey there is a nice format with growing adoption” :)

**Comment by josephwright** [comment] 2018-05-16 13:30
I'm going to go, as @Evpok suggests, with the format from keepachengelog: looks OK to me. Expect stubs to be checked in today (I'll also look at `l3build`).

**Closed** 2018-05-16 13:51 UTC
Labels: documentation, enhancement

**Comment by josephwright** [comment] 2018-05-16 14:35
@FrankMittelbach  My understanding is that a ChangeLog should (typically) have short entries with the 'headlines', so for a syntax change we might have '\cs{cs_generate_variant:Nn} is now stricter about variant types' in the change log, whilst in the syntax changes file we cover the change in some detail. On the other hand, I'm only starting from the turn of the year here, so we could just put new information in the change log. (We probably do want to keep the separate tabulated deprecation list in `l3obsolete.txt`.)

**Comment by blefloch** [comment] 2018-05-16 15:11
Definitely keep l3obsolete.  It seems to me that l3syntax-changes is
useful in that it lists breaking changes (and hopefully all of them).
Is there a way to mark-up the breaking changes in the changelog so that
they can easily be searched for?

**Comment by josephwright** [comment] 2018-05-16 15:13
@blefloch  Of course: we just have to have an agreed test: most obviously something like `[breaking]` or perhaps simple `*` with a note at the top of the file.
